## Question 1: 
1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: A)
Rank
B) Name
C) Artist
D) Upload date
E) Views

In [2]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
import warnings
warnings.filterwarnings('ignore')

In [2]:
driver=webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [3]:
heads=[]
tab_heads=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/thead/tr/th')
for head in tab_heads:
    
    #if head=='':
     #   heads.append('-')
    #else:
    heads.append(head.text)

In [4]:
heads

['Video name', 'Uploader', 'Views (billions)', 'Date', '']

In [5]:
table_contents=[]
tab_con=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td')
for con in tab_con:
    table_contents.append(con.text)

In [6]:
table_contents

['"Baby Shark Dance"[7]',
 "Pinkfong Baby Shark - Kids' Songs & Stories",
 '14.52',
 'June 17, 2016',
 '[A]',
 '"Despacito"[10]',
 'Luis Fonsi',
 '8.44',
 'January 12, 2017',
 '[B]',
 '"Johny Johny Yes Papa"[18]',
 "LooLoo Kids - Nursery Rhymes and Children's Songs",
 '6.91',
 'October 8, 2016',
 '',
 '"Bath Song"[19]',
 'Cocomelon - Nursery Rhymes',
 '6.70',
 'May 2, 2018',
 '',
 '"See You Again"[20]',
 'Wiz Khalifa',
 '6.27',
 'April 6, 2015',
 '[C]',
 '"Shape of You"[25]',
 'Ed Sheeran',
 '6.26',
 'January 30, 2017',
 '[D]',
 '"Wheels on the Bus"[28]',
 'Cocomelon - Nursery Rhymes',
 '6.13',
 'May 24, 2018',
 '',
 '"Phonics Song with Two Words"[29]',
 'ChuChu TV Nursery Rhymes & Kids Songs',
 '5.80',
 'March 6, 2014',
 '',
 '"Uptown Funk"[30]',
 'Mark Ronson',
 '5.23',
 'November 19, 2014',
 '',
 '"Gangnam Style"[31]',
 'Psy',
 '5.15',
 'July 15, 2012',
 '[E]',
 '"Learning Colors – Colorful Eggs on a Farm"[36]',
 'Miroshka TV',
 '5.11',
 'February 27, 2018',
 '',
 '"Dame Tu Cosita"[37]',
 'Ultra Records',
 '4.63',
 'April 5, 2018',
 '',
 '"Masha and the Bear – Recipe for Disaster"[38]',
 'Get Movies',
 '4.58',
 'January 31, 2012',
 '',
 '"Axel F"[39]',
 'Crazy Frog',
 '4.54',
 'June 16, 2009',
 '',
 '"Baa Baa Black Sheep"[40]',
 'Cocomelon - Nursery Rhymes',
 '4.05',
 'June 25, 2018',
 '',
 '"Sugar"[41]',
 'Maroon 5',
 '4.05',
 'January 14, 2015',
 '',
 '"Lakdi Ki Kathi"[42]',
 'Jingle Toons',
 '4.04',
 'June 14, 2018',
 '',
 '"Counting Stars"[43]',
 'OneRepublic',
 '4.02',
 'May 31, 2013',
 '',
 '"Roar"[44]',
 'Katy Perry',
 '4.00',
 'September 5, 2013',
 '',
 '"Waka Waka (This Time for Africa)"[45]',
 'Shakira',
 '3.93',
 'June 4, 2010',
 '',
 '"Shree Hanuman Chalisa"[46]',
 'T-Series Bhakti Sagar',
 '3.84',
 'May 10, 2011',
 '',
 '"Humpty the train on a fruits ride"[47]',
 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs',
 '3.81',
 'January 26, 2018',
 '',
 '"Sorry"[48]',
 'Justin Bieber',
 '3.80',
 'October 22, 2015',
 '',
 '"Thinking Out Loud"[49]',
 'Ed Sheeran',
 '3.77',
 'October 7, 2014',
 '',
 '"Perfect"[50]',
 'Ed Sheeran',
 '3.74',
 'November 9, 2017',
 '',
 '"Dark Horse"[51]',
 'Katy Perry',
 '3.72',
 'February 20, 2014',
 '',
 '"Let Her Go"[52]',
 'Passenger',
 '3.66',
 'July 25, 2012',
 '',
 '"Faded"[53]',
 'Alan Walker',
 '3.63',
 'December 3, 2015',
 '',
 '"Girls Like You"[54]',
 'Maroon 5',
 '3.61',
 'May 31, 2018',
 '',
 '"Lean On"[55]',
 'Major Lazer Official',
 '3.60',
 'March 22, 2015',
 '']

In [7]:
import numpy as np
rows=np.array(table_contents)
tabrows=rows.reshape(30,5)

In [8]:
import pandas as pd
most_viewed=pd.DataFrame(tabrows,columns=heads)

In [9]:
most_viewed.index.name='Rank'

In [10]:
most_viewed.drop(columns=[''],inplace=True)

In [11]:
most_viewed

,Video name,Uploader,Views (billions),Date
Rank,,,,
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,14.52,"June 17, 2016"
1,"""Despacito""[10]",Luis Fonsi,8.44,"January 12, 2017"
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.91,"October 8, 2016"
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,6.70,"May 2, 2018"
4,"""See You Again""[20]",Wiz Khalifa,6.27,"April 6, 2015"
5,"""Shape of You""[25]",Ed Sheeran,6.26,"January 30, 2017"
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,6.13,"May 24, 2018"
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,5.80,"March 6, 2014"
8,"""Uptown Funk""[30]",Mark Ronson,5.23,"November 19, 2014"
9,"""Gangnam Style""[31]",Psy,5.15,"July 15, 2012"
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,5.11,"February 27, 2018"
11,"""Dame Tu Cosita""[37]",Ultra Records,4.63,"April 5, 2018"
12,"""Masha and the Bear – Recipe for Disaster""[38]",Get Movies,4.58,"January 31, 2012"
13,"""Axel F""[39]",Crazy Frog,4.54,"June 16, 2009"
14,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,4.05,"June 25, 2018"
15,"""Sugar""[41]",Maroon 5,4.05,"January 14, 2015"
16,"""Lakdi Ki Kathi""[42]",Jingle Toons,4.04,"June 14, 2018"
17,"""Counting Stars""[43]",OneRepublic,4.02,"May 31, 2013"
18,"""Roar""[44]",Katy Perry,4.00,"September 5, 2013"
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,3.93,"June 4, 2010"
20,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,3.84,"May 10, 2011"
21,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.81,"January 26, 2018"
22,"""Sorry""[48]",Justin Bieber,3.80,"October 22, 2015"
23,"""Thinking Out Loud""[49]",Ed Sheeran,3.77,"October 7, 2014"
24,"""Perfect""[50]",Ed Sheeran,3.74,"November 9, 2017"
25,"""Dark Horse""[51]",Katy Perry,3.72,"February 20, 2014"
26,"""Let Her Go""[52]",Passenger,3.66,"July 25, 2012"
27,"""Faded""[53]",Alan Walker,3.63,"December 3, 2015"
28,"""Girls Like You""[54]",Maroon 5,3.61,"May 31, 2018"
29,"""Lean On""[55]",Major Lazer Official,3.60,"March 22, 2015"

## Question 2:
Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Series
B) Place
C) Date
D) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [24]:
#Automating Chrome
driver2=webdriver.Chrome()
driver2.get('https://www.bcci.tv/')

In [34]:
#Going to Fixtures page:
def page_fixtures():
    fixtures_page=WebDriverWait(driver2,20).until(EC.element_to_be_clickable((By.XPATH,'//div[@class="imw-tabs international-tabs"]/a[2]')))
    #fixtures_page=driver2.find_element(By.XPATH,'//div[@class="imw-tabs international-tabs"]/a[2]')
    fix=fixtures_page.get_attribute('href')
    driver2.get(fix)

In [37]:
series_name=[]
def name_series():
    home()
    time.sleep(10)
   
    try:
        page_fixtures()
        time.sleep(20)
    except TimeoutException:
        time.sleep(30)
    try:
        more_button=WebDriverWait(driver2, 10).until(EC.element_to_be_clickable((By.XPATH, '//div[@class="fixture-tab-inner row ng-scope"]/div/button')))
        for i in range(1):
            more_button.click()
            time.sleep(5)
    except TimeoutException:
        print("element not found yet")
        
    
    series=driver2.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    for sr in series:
        series_name.append(sr.text)

In [38]:
name_series()

In [39]:
series_name

['ICC Mens T20 World Cup 2024',
 'ICC Mens T20 World Cup 2024',
 'South Africa Women Tour Of India 2024',
 'ICC Mens T20 World Cup 2024',
 'South Africa Women Tour Of India 2024',
 'South Africa Women Tour Of India 2024',
 'South Africa Women Tour Of India 2024',
 'South Africa Women Tour Of India 2024',
 'South Africa Women Tour Of India 2024',
 'India Tour Of Zimbabwe 2024',
 'South Africa Women Tour Of India 2024',
 'India Tour Of Zimbabwe 2024',
 'South Africa Women Tour Of India 2024',
 'India Tour Of Zimbabwe 2024',
 'India Tour Of Zimbabwe 2024',
 'India Tour Of Zimbabwe 2024',
 'ICC Womens T20 World Cup 2024',
 'ICC Womens T20 World Cup 2024',
 'ICC Womens T20 World Cup 2024',
 'ICC Womens T20 World Cup 2024']

In [40]:
series_place=[]
def place_series():
    home()
    time.sleep(10)
   
    try:
        page_fixtures()
        time.sleep(20)
    except TimeoutException:
        time.sleep(30)
    try:
        more_button=WebDriverWait(driver2, 10).until(EC.element_to_be_clickable((By.XPATH, '//div[@class="fixture-tab-inner row ng-scope"]/div/button')))
        for i in range(1):
            more_button.click()
            time.sleep(5)
    except TimeoutException:
        print("element not found yet")
        
    
    place=driver2.find_elements(By.XPATH,'//div[@class="match-venue ng-scope"]')
    for pl in place:
        series_place.append(pl.text)

In [41]:
place_series()

In [42]:
series_place

['Nassau County International Cricket Stadium, New York',
 'Nassau County International Cricket Stadium, New York',
 'M Chinnaswamy Stadium, Bengaluru',
 'Central Broward Park & Broward County Stadium, Lauderhill, Florida',
 'M Chinnaswamy Stadium, Bengaluru',
 'M Chinnaswamy Stadium, Bengaluru',
 'M Chinnaswamy Stadium, Bengaluru',
 'MA Chidambaram Stadium, Chennai',
 'MA Chidambaram Stadium, Chennai',
 'Harare Sports Club, Harare',
 'MA Chidambaram Stadium, Chennai',
 'Harare Sports Club, Harare',
 'MA Chidambaram Stadium, Chennai',
 'Harare Sports Club, Harare',
 'Harare Sports Club, Harare',
 'Harare Sports Club, Harare',
 'Sylhet International Cricket Stadium, Sylhet',
 'Sylhet International Cricket Stadium, Sylhet',
 'Sylhet International Cricket Stadium, Sylhet',
 'Sylhet International Cricket Stadium, Sylhet']

In [43]:
series_date=[]
def date_series():
    home()
    time.sleep(10)
   
    try:
        page_fixtures()
        time.sleep(20)
    except TimeoutException:
        time.sleep(30)
    try:
        more_button=WebDriverWait(driver2, 10).until(EC.element_to_be_clickable((By.XPATH, '//div[@class="fixture-tab-inner row ng-scope"]/div/button')))
        for i in range(1):
            more_button.click()
            time.sleep(5)
    except TimeoutException:
        print("element not found yet")
        
    
    date=driver2.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for dt in date:
        series_date.append(dt.text)

In [44]:
date_series()

In [45]:
series_date

['9 Jun',
 '12 Jun',
 '13 Jun',
 '15 Jun',
 '16 Jun',
 '19 Jun',
 '23 Jun',
 '28 Jun',
 '5 Jul',
 '6 Jul',
 '7 Jul',
 '7 Jul',
 '9 Jul',
 '10 Jul',
 '13 Jul',
 '14 Jul',
 '4 Oct',
 '6 Oct',
 '9 Oct',
 '13 Oct']

In [48]:
series_time=[]
def time_series():
    home()
    time.sleep(10)
   
    try:
        page_fixtures()
        time.sleep(20)
    except TimeoutException:
        time.sleep(30)
    try:
        more_button=WebDriverWait(driver2, 10).until(EC.element_to_be_clickable((By.XPATH, '//div[@class="fixture-tab-inner row ng-scope"]/div/button')))
        for i in range(1):
            more_button.click()
            time.sleep(5)
    except TimeoutException:
        print("element not found yet")
        
    
    times=driver2.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    for tm in times:
        series_time.append(tm.text)

In [49]:
time_series()

In [50]:
series_time

['18:30 GST',
 '18:30 GST',
 '12:00 GST',
 '18:30 GST',
 '12:00 GST',
 '12:00 GST',
 '12:00 GST',
 '8:00 GST',
 '17:30 GST',
 '18:30 GST',
 '17:30 GST',
 '18:30 GST',
 '17:30 GST',
 '18:30 GST',
 '18:30 GST',
 '18:30 GST',
 '17:00',
 '17:00',
 '17:00',
 '17:00']

In [51]:
import pandas as pd
data={'Name of Series':series_name,'Place of Series':series_place,'Date of Series':series_date,'Time of series':series_time}
Data_series=pd.DataFrame(data)

In [52]:
Data_series

,Name of Series,Place of Series,Date of Series,Time of series
0,ICC Mens T20 World Cup 2024,"Nassau County International Cricket Stadium, N...",9 Jun,18:30 GST
1,ICC Mens T20 World Cup 2024,"Nassau County International Cricket Stadium, N...",12 Jun,18:30 GST
2,South Africa Women Tour Of India 2024,"M Chinnaswamy Stadium, Bengaluru",13 Jun,12:00 GST
3,ICC Mens T20 World Cup 2024,"Central Broward Park & Broward County Stadium,...",15 Jun,18:30 GST
4,South Africa Women Tour Of India 2024,"M Chinnaswamy Stadium, Bengaluru",16 Jun,12:00 GST
5,South Africa Women Tour Of India 2024,"M Chinnaswamy Stadium, Bengaluru",19 Jun,12:00 GST
6,South Africa Women Tour Of India 2024,"M Chinnaswamy Stadium, Bengaluru",23 Jun,12:00 GST
7,South Africa Women Tour Of India 2024,"MA Chidambaram Stadium, Chennai",28 Jun,8:00 GST
8,South Africa Women Tour Of India 2024,"MA Chidambaram Stadium, Chennai",5 Jul,17:30 GST
9,India Tour Of Zimbabwe 2024,"Harare Sports Club, Harare",6 Jul,18:30 GST
10,South Africa Women Tour Of India 2024,"MA Chidambaram Stadium, Chennai",7 Jul,17:30 GST
11,India Tour Of Zimbabwe 2024,"Harare Sports Club, Harare",7 Jul,18:30 GST
12,South Africa Women Tour Of India 2024,"MA Chidambaram Stadium, Chennai",9 Jul,17:30 GST
13,India Tour Of Zimbabwe 2024,"Harare Sports Club, Harare",10 Jul,18:30 GST
14,India Tour Of Zimbabwe 2024,"Harare Sports Club, Harare",13 Jul,18:30 GST
15,India Tour Of Zimbabwe 2024,"Harare Sports Club, Harare",14 Jul,18:30 GST
16,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",4 Oct,17:00
17,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",6 Oct,17:00
18,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",9 Oct,17:00
19,ICC Womens T20 World Cup 2024,"Sylhet International Cricket Stadium, Sylhet",13 Oct,17:00

## Question 3:
Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details: A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [77]:
driver3=webdriver.Chrome()
driver3.get('http://statisticstimes.com/')

In [78]:
economy_page=WebDriverWait(driver3,10).until(EC.element_to_be_clickable((By.XPATH,'//div[@class="navbar"]/div[2]/button')))
economy_page.click()
india_page=driver3.find_element(By.XPATH,'//div[@class="dropdown-content"]/a[3]')
india_href=india_page.get_attribute('href')
driver3.get(india_href)

In [79]:
tab_page=driver3.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
tab_href=tab_page.get_attribute('href')
driver3.get(tab_href)

In [80]:
table_row1=[]
tab=driver3.find_elements(By.XPATH,'//div[@id="main"]/div[5]/div/div/table[1]/thead/tr[1]/th')
for tb in tab:
    table_row1.append(tb.text)
table_row1

['Rank',
 'State',
 'GSDP (Cr INR at Current prices)',
 'Share',
 'GDP ($billion)',
 'GSDP (Cr INR at 2011-12 prices)']

In [81]:
table_row2=[]
tab=driver3.find_elements(By.XPATH,'//div[@id="main"]/div[5]/div/div/table[1]/thead/tr/th')
for tb in tab:
    table_row2.append(tb.text)
table_row2

['23-24', '22-23', '21-22', '21-22', '2021', '23-24', '22-23', '21-22']

In [85]:
table_body=[]
body=driver3.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr')
for bd in body:
    table_body.append(bd.text)
table_body

['1 Maharashtra - - 3,108,022 13.17% 414.928 - - 2,027,971',
 '2 Tamil Nadu 2,700,109 2,364,514 2,071,286 8.78% 276.522 1,572,601 1,453,321 1,343,287',
 '3 Karnataka 2,500,733 2,269,995 1,978,094 8.38% 264.080 1,423,229 1,335,052 1,235,377',
 '4 Uttar Pradesh 2,547,861 2,258,040 1,975,595 8.37% 263.747 1,423,358 1,318,027 1,200,093',
 '5 Gujarat - 2,230,609 1,928,683 8.17% 257.484 - 1,475,629 1,365,922',
 '6 West Bengal 1,700,939 1,531,758 1,329,238 5.63% 177.456 904,088 839,805 787,439',
 '7 Rajasthan 1,524,030 1,365,849 1,193,489 5.06% 159.334 842,621 784,655 727,805',
 '8 Andhra Pradesh 1,439,674 1,303,524 1,148,471 4.87% 153.324 820,894 764,685 722,727',
 '9 Telangana 1,463,960 1,308,034 1,124,204 4.76% 150.084 767,936 715,157 669,229',
 '10 Madhya Pradesh 1,363,327 1,246,471 1,092,964 4.63% 145.913 660,363 622,908 584,470',
 '11 Kerala - 1,046,188 934,542 3.96% 124.764 - 616,189 578,057',
 '12 Delhi 1,107,746 1,014,688 881,336 3.73% 117.660 672,247 625,981 580,396',
 '13 Haryana 1,095,535 984,055 868,905 3.68% 116.001 634,027 587,198 544,317',
 '14 Odisha 832,790 753,177 662,886 2.81% 88.497 503,871 464,574 430,541',
 '15 Bihar - 751,396 650,302 2.76% 86.817 - 442,473 399,930',
 '16 Punjab 736,423 676,164 617,192 2.62% 82.397 493,283 462,053 434,261',
 '17 Assam 565,401 493,167 411,454 1.74% 54.930 318,559 300,799 278,835',
 '18 Chhattisgarh 505,887 464,399 410,525 1.74% 54.806 321,945 302,119 280,609',
 '19 Jharkhand - 393,722 358,863 1.52% 47.909 - 259,800 243,348',
 '20 Uttarakhand 346,206 303,781 267,143 1.13% 35.664 213,378 198,341 184,274',
 '21 Jammu & Kashmir 246,465 224,226 193,352 0.82% 25.813 139,171 129,573 119,174',
 '22 Himachal Pradesh 207,430 191,728 172,162 0.73% 22.984 142,800 133,372 124,770',
 '23 Goa - 93,672 84,266 0.36% 11.250 - 59,867 55,342',
 '24 Tripura - 72,636 62,550 0.27% 8.351 - 42,997 39,487',
 '25 Chandigarh - 54,285 46,096 0.20% 6.154 - 33,879 30,587',
 '26 Puducherry - 49,643 43,810 0.19% 5.849 - 28,849 27,131',
 '27 Meghalaya 47,381 42,697 38,785 0.16% 5.178 26,524 25,209 24,267',
 '28 Sikkim - 42,756 37,557 0.16% 5.014 - 22,144 20,728',
 '29 Manipur - - 36,594 0.16% 4.885 - - 20,515',
 '30 Arunachal Pradesh - 39,630 34,775 0.15% 4.643 - 21,085 19,707',
 '31 Nagaland - 35,643 31,038 0.13% 4.144 - 18,993 17,336',
 '32 Mizoram - - 27,824 0.12% 3.715 - - 18,494',
 '33 Andaman & Nicobar Islands - - 10,371 0.04% 1.385 - - 7,172',
 '1 Maharashtra - - 2,690,525 13.03% - - 1,731,189',
 '2 Tamil Nadu 2,417,237 2,115,510 1,854,109 8.98% 1,384,921 1,279,878 1,182,919',
 '3 Karnataka 2,261,867 2,055,658 1,790,456 8.67% 1,263,925 1,187,557 1,098,510',
 '4 Uttar Pradesh 2,217,055 1,962,865 1,715,328 8.31% 1,206,156 1,116,011 1,014,396',
 '5 Gujarat - 1,946,334 1,700,504 8.23% - 1,301,070 1,198,007',
 '6 West Bengal 1,531,371 1,378,859 1,199,587 5.81% 791,144 735,049 692,592',
 '7 Rajasthan 1,366,626 1,222,507 1,068,864 5.18% 737,042 686,211 637,616',
 '8 Andhra Pradesh 1,291,518 1,167,107 1,030,465 4.99% 723,343 672,455 636,219',
 '9 Telangana 1,326,022 1,184,237 1,017,859 4.93% 679,552 633,091 591,472',
 '10 Madhya Pradesh 1,242,883 1,137,254 993,235 4.81% 579,234 546,005 512,117',
 '11 Kerala - 933,564 825,010 3.99% - 564,164 528,323',
 '12 Delhi 997,171 911,639 782,570 3.79% 590,836 548,826 507,595',
 '13 Haryana 985,877 885,029 778,885 3.77% 561,368 519,135 480,417',
 '14 Bihar - 681,761 589,712 2.86% - 394,114 356,057',
 '15 Odisha 749,809 670,196 579,905 2.81% 443,233 403,936 369,904',
 '16 Punjab 639,252 588,712 540,097 2.62% 424,857 399,400 376,909',
 '17 Assam 487,584 428,072 366,359 1.77% 288,842 264,089 246,203',
 '18 Chhattisgarh 447,682 412,494 365,028 1.77% 279,803 263,839 245,947',
 '19 Jharkhand - 360,689 325,830 1.58% - 235,685 219,234',
 '20 Uttarakhand 304,592 267,653 235,376 1.14% 186,484 173,280 160,921',
 '21 Jammu & Kashmir 200,046 181,383 156,907 0.76% 108,830 100,849 92,690',
 '22 Himachal Pradesh 176,164 163,062 145,182 0.70% 120,733 112,633 105,500',
 '23 Goa - 83,711 74,305 0.36% - 52,426 47,901',
 '24 Tripura - 65,808 56,226 0.27% - 37,917 34,851',
 '25 Chandigarh - 48,261 41,011 0.20% - 29,957 26,985',
 '26 Puducherry - 44,809 39,787 0.19% - 25,652 24,136',
 '27 Meghalaya 42,214 37,925 34,441 0.17% 23,063 21,905 21,096',
 '28 Manipur - - 32,874 0.16% - - 17,810',
 '29 Sikkim - 35,670 31,519 0.15% - 17,832 16,764',
 '30 Arunachal Pradesh - 35,555 31,420 0.15% - 18,273 17,196',
 '31 Nagaland - 30,957 26,924 0.13% - 14,307 13,222',
 '32 Mizoram - - 24,293 0.12% - - 15,847',
 '33 Andaman & Nicobar Islands - - 9,209 0.04% - - 6,558']

In [90]:
del table_body[33:-1]

In [91]:
table_body

['1 Maharashtra - - 3,108,022 13.17% 414.928 - - 2,027,971',
 '2 Tamil Nadu 2,700,109 2,364,514 2,071,286 8.78% 276.522 1,572,601 1,453,321 1,343,287',
 '3 Karnataka 2,500,733 2,269,995 1,978,094 8.38% 264.080 1,423,229 1,335,052 1,235,377',
 '4 Uttar Pradesh 2,547,861 2,258,040 1,975,595 8.37% 263.747 1,423,358 1,318,027 1,200,093',
 '5 Gujarat - 2,230,609 1,928,683 8.17% 257.484 - 1,475,629 1,365,922',
 '6 West Bengal 1,700,939 1,531,758 1,329,238 5.63% 177.456 904,088 839,805 787,439',
 '7 Rajasthan 1,524,030 1,365,849 1,193,489 5.06% 159.334 842,621 784,655 727,805',
 '8 Andhra Pradesh 1,439,674 1,303,524 1,148,471 4.87% 153.324 820,894 764,685 722,727',
 '9 Telangana 1,463,960 1,308,034 1,124,204 4.76% 150.084 767,936 715,157 669,229',
 '10 Madhya Pradesh 1,363,327 1,246,471 1,092,964 4.63% 145.913 660,363 622,908 584,470',
 '11 Kerala - 1,046,188 934,542 3.96% 124.764 - 616,189 578,057',
 '12 Delhi 1,107,746 1,014,688 881,336 3.73% 117.660 672,247 625,981 580,396',
 '13 Haryana 1,095,535 984,055 868,905 3.68% 116.001 634,027 587,198 544,317',
 '14 Odisha 832,790 753,177 662,886 2.81% 88.497 503,871 464,574 430,541',
 '15 Bihar - 751,396 650,302 2.76% 86.817 - 442,473 399,930',
 '16 Punjab 736,423 676,164 617,192 2.62% 82.397 493,283 462,053 434,261',
 '17 Assam 565,401 493,167 411,454 1.74% 54.930 318,559 300,799 278,835',
 '18 Chhattisgarh 505,887 464,399 410,525 1.74% 54.806 321,945 302,119 280,609',
 '19 Jharkhand - 393,722 358,863 1.52% 47.909 - 259,800 243,348',
 '20 Uttarakhand 346,206 303,781 267,143 1.13% 35.664 213,378 198,341 184,274',
 '21 Jammu & Kashmir 246,465 224,226 193,352 0.82% 25.813 139,171 129,573 119,174',
 '22 Himachal Pradesh 207,430 191,728 172,162 0.73% 22.984 142,800 133,372 124,770',
 '23 Goa - 93,672 84,266 0.36% 11.250 - 59,867 55,342',
 '24 Tripura - 72,636 62,550 0.27% 8.351 - 42,997 39,487',
 '25 Chandigarh - 54,285 46,096 0.20% 6.154 - 33,879 30,587',
 '26 Puducherry - 49,643 43,810 0.19% 5.849 - 28,849 27,131',
 '27 Meghalaya 47,381 42,697 38,785 0.16% 5.178 26,524 25,209 24,267',
 '28 Sikkim - 42,756 37,557 0.16% 5.014 - 22,144 20,728',
 '29 Manipur - - 36,594 0.16% 4.885 - - 20,515',
 '30 Arunachal Pradesh - 39,630 34,775 0.15% 4.643 - 21,085 19,707',
 '31 Nagaland - 35,643 31,038 0.13% 4.144 - 18,993 17,336',
 '32 Mizoram - - 27,824 0.12% 3.715 - - 18,494',
 '33 Andaman & Nicobar Islands - - 10,371 0.04% 1.385 - - 7,172']

In [74]:
table_body.clear()

In [92]:
len(table_body)

33

In [94]:
pattern = re.compile(r'(\d+)\s+([A-Za-z &]+)\s+(.*)')

new_body = []

for line in table_body:
    match = pattern.match(line)
    if match:
        rank = match.group(1)
        state = match.group(2).strip()
        rest = match.group(3).strip()
        # Split the remaining values on spaces
        values = rest.split()
        # Create a fixed length list of 10 elements
        fixed_length_entry = [rank, state] + values
        if len(fixed_length_entry) < 10:
            fixed_length_entry.extend([''] * (10 - len(fixed_length_entry)))
        elif len(fixed_length_entry) > 10:
            fixed_length_entry = fixed_length_entry[:10]
        new_body.append(fixed_length_entry)

# Convert to numpy array
array_data = np.array(new_body)

# Check the shape to ensure it's 33x10
print("Shape of the array:", array_data.shape)

# Display the array
print(array_data)

Shape of the array: (33, 10)
[['1' 'Maharashtra' '-' '-' '3,108,022' '13.17%' '414.928' '-' '-'
  '2,027,971']
 ['2' 'Tamil Nadu' '2,700,109' '2,364,514' '2,071,286' '8.78%' '276.522'
  '1,572,601' '1,453,321' '1,343,287']
 ['3' 'Karnataka' '2,500,733' '2,269,995' '1,978,094' '8.38%' '264.080'
  '1,423,229' '1,335,052' '1,235,377']
 ['4' 'Uttar Pradesh' '2,547,861' '2,258,040' '1,975,595' '8.37%'
  '263.747' '1,423,358' '1,318,027' '1,200,093']
 ['5' 'Gujarat' '-' '2,230,609' '1,928,683' '8.17%' '257.484' '-'
  '1,475,629' '1,365,922']
 ['6' 'West Bengal' '1,700,939' '1,531,758' '1,329,238' '5.63%' '177.456'
  '904,088' '839,805' '787,439']
 ['7' 'Rajasthan' '1,524,030' '1,365,849' '1,193,489' '5.06%' '159.334'
  '842,621' '784,655' '727,805']
 ['8' 'Andhra Pradesh' '1,439,674' '1,303,524' '1,148,471' '4.87%'
  '153.324' '820,894' '764,685' '722,727']
 ['9' 'Telangana' '1,463,960' '1,308,034' '1,124,204' '4.76%' '150.084'
  '767,936' '715,157' '669,229']
 ['10' 'Madhya Pradesh' '1,363,327' '1,246,471' '1,092,964' '4.63%'
  '145.913' '660,363' '622,908' '584,470']
 ['11' 'Kerala' '-' '1,046,188' '934,542' '3.96%' '124.764' '-' '616,189'
  '578,057']
 ['12' 'Delhi' '1,107,746' '1,014,688' '881,336' '3.73%' '117.660'
  '672,247' '625,981' '580,396']
 ['13' 'Haryana' '1,095,535' '984,055' '868,905' '3.68%' '116.001'
  '634,027' '587,198' '544,317']
 ['14' 'Odisha' '832,790' '753,177' '662,886' '2.81%' '88.497' '503,871'
  '464,574' '430,541']
 ['15' 'Bihar' '-' '751,396' '650,302' '2.76%' '86.817' '-' '442,473'
  '399,930']
 ['16' 'Punjab' '736,423' '676,164' '617,192' '2.62%' '82.397' '493,283'
  '462,053' '434,261']
 ['17' 'Assam' '565,401' '493,167' '411,454' '1.74%' '54.930' '318,559'
  '300,799' '278,835']
 ['18' 'Chhattisgarh' '505,887' '464,399' '410,525' '1.74%' '54.806'
  '321,945' '302,119' '280,609']
 ['19' 'Jharkhand' '-' '393,722' '358,863' '1.52%' '47.909' '-' '259,800'
  '243,348']
 ['20' 'Uttarakhand' '346,206' '303,781' '267,143' '1.13%' '35.664'
  '213,378' '198,341' '184,274']
 ['21' 'Jammu & Kashmir' '246,465' '224,226' '193,352' '0.82%' '25.813'
  '139,171' '129,573' '119,174']
 ['22' 'Himachal Pradesh' '207,430' '191,728' '172,162' '0.73%' '22.984'
  '142,800' '133,372' '124,770']
 ['23' 'Goa' '-' '93,672' '84,266' '0.36%' '11.250' '-' '59,867' '55,342']
 ['24' 'Tripura' '-' '72,636' '62,550' '0.27%' '8.351' '-' '42,997'
  '39,487']
 ['25' 'Chandigarh' '-' '54,285' '46,096' '0.20%' '6.154' '-' '33,879'
  '30,587']
 ['26' 'Puducherry' '-' '49,643' '43,810' '0.19%' '5.849' '-' '28,849'
  '27,131']
 ['27' 'Meghalaya' '47,381' '42,697' '38,785' '0.16%' '5.178' '26,524'
  '25,209' '24,267']
 ['28' 'Sikkim' '-' '42,756' '37,557' '0.16%' '5.014' '-' '22,144'
  '20,728']
 ['29' 'Manipur' '-' '-' '36,594' '0.16%' '4.885' '-' '-' '20,515']
 ['30' 'Arunachal Pradesh' '-' '39,630' '34,775' '0.15%' '4.643' '-'
  '21,085' '19,707']
 ['31' 'Nagaland' '-' '35,643' '31,038' '0.13%' '4.144' '-' '18,993'
  '17,336']
 ['32' 'Mizoram' '-' '-' '27,824' '0.12%' '3.715' '-' '-' '18,494']
 ['33' 'Andaman & Nicobar Islands' '-' '-' '10,371' '0.04%' '1.385' '-'
  '-' '7,172']]

In [95]:
for u,i in enumerate(new_body):
    print(u+1,'---',len(i))

1 --- 10
2 --- 10
3 --- 10
4 --- 10
5 --- 10
6 --- 10
7 --- 10
8 --- 10
9 --- 10
10 --- 10
11 --- 10
12 --- 10
13 --- 10
14 --- 10
15 --- 10
16 --- 10
17 --- 10
18 --- 10
19 --- 10
20 --- 10
21 --- 10
22 --- 10
23 --- 10
24 --- 10
25 --- 10
26 --- 10
27 --- 10
28 --- 10
29 --- 10
30 --- 10
31 --- 10
32 --- 10
33 --- 10

In [62]:
import numpy as np

In [96]:
body=np.array(new_body)

In [98]:
body.shape

(33, 10)

In [9]:
headings=['Rank','State','GDP 2023-24','GDP 2022-23','GDP 2021-22','Share 2021-22','GDP ($ Billion)','GSDP 2023-24','GSDP 2022-23','GSDP 2021-22']

In [10]:
headings

['Rank',
 'State',
 'GDP 2023-24',
 'GDP 2022-23',
 'GDP 2021-22',
 'Share 2021-22',
 'GDP ($ Billion)',
 'GSDP 2023-24',
 'GSDP 2022-23',
 'GSDP 2021-22']

In [99]:
import pandas as pd
states=pd.DataFrame(data=body,columns=headings)

In [100]:
states

,Rank,State,GDP 2023-24,GDP 2022-23,GDP 2021-22,Share 2021-22,GDP ($ Billion),GSDP 2023-24,GSDP 2022-23,GSDP 2021-22
0,1,Maharashtra,-,-,"3,108,022",13.17%,414.928,-,-,"2,027,971"
1,2,Tamil Nadu,"2,700,109","2,364,514","2,071,286",8.78%,276.522,"1,572,601","1,453,321","1,343,287"
2,3,Karnataka,"2,500,733","2,269,995","1,978,094",8.38%,264.080,"1,423,229","1,335,052","1,235,377"
3,4,Uttar Pradesh,"2,547,861","2,258,040","1,975,595",8.37%,263.747,"1,423,358","1,318,027","1,200,093"
4,5,Gujarat,-,"2,230,609","1,928,683",8.17%,257.484,-,"1,475,629","1,365,922"
5,6,West Bengal,"1,700,939","1,531,758","1,329,238",5.63%,177.456,"904,088","839,805","787,439"
6,7,Rajasthan,"1,524,030","1,365,849","1,193,489",5.06%,159.334,"842,621","784,655","727,805"
7,8,Andhra Pradesh,"1,439,674","1,303,524","1,148,471",4.87%,153.324,"820,894","764,685","722,727"
8,9,Telangana,"1,463,960","1,308,034","1,124,204",4.76%,150.084,"767,936","715,157","669,229"
9,10,Madhya Pradesh,"1,363,327","1,246,471","1,092,964",4.63%,145.913,"660,363","622,908","584,470"
10,11,Kerala,-,"1,046,188","934,542",3.96%,124.764,-,"616,189","578,057"
11,12,Delhi,"1,107,746","1,014,688","881,336",3.73%,117.660,"672,247","625,981","580,396"
12,13,Haryana,"1,095,535","984,055","868,905",3.68%,116.001,"634,027","587,198","544,317"
13,14,Odisha,"832,790","753,177","662,886",2.81%,88.497,"503,871","464,574","430,541"
14,15,Bihar,-,"751,396","650,302",2.76%,86.817,-,"442,473","399,930"
15,16,Punjab,"736,423","676,164","617,192",2.62%,82.397,"493,283","462,053","434,261"
16,17,Assam,"565,401","493,167","411,454",1.74%,54.930,"318,559","300,799","278,835"
17,18,Chhattisgarh,"505,887","464,399","410,525",1.74%,54.806,"321,945","302,119","280,609"
18,19,Jharkhand,-,"393,722","358,863",1.52%,47.909,-,"259,800","243,348"
19,20,Uttarakhand,"346,206","303,781","267,143",1.13%,35.664,"213,378","198,341","184,274"
20,21,Jammu & Kashmir,"246,465","224,226","193,352",0.82%,25.813,"139,171","129,573","119,174"
21,22,Himachal Pradesh,"207,430","191,728","172,162",0.73%,22.984,"142,800","133,372","124,770"
22,23,Goa,-,"93,672","84,266",0.36%,11.250,-,"59,867","55,342"
23,24,Tripura,-,"72,636","62,550",0.27%,8.351,-,"42,997","39,487"
24,25,Chandigarh,-,"54,285","46,096",0.20%,6.154,-,"33,879","30,587"
25,26,Puducherry,-,"49,643","43,810",0.19%,5.849,-,"28,849","27,131"
26,27,Meghalaya,"47,381","42,697","38,785",0.16%,5.178,"26,524","25,209","24,267"
27,28,Sikkim,-,"42,756","37,557",0.16%,5.014,-,"22,144","20,728"
28,29,Manipur,-,-,"36,594",0.16%,4.885,-,-,"20,515"
29,30,Arunachal Pradesh,-,"39,630","34,775",0.15%,4.643,-,"21,085","19,707"
30,31,Nagaland,-,"35,643","31,038",0.13%,4.144,-,"18,993","17,336"
31,32,Mizoram,-,-,"27,824",0.12%,3.715,-,-,"18,494"
32,33,Andaman & Nicobar Islands,-,-,"10,371",0.04%,1.385,-,-,"7,172"

Since the data expected in the question was not present in the table in the website, hence i have kept the table as it is. We can always delete the undesired columns using the drop method i.e states.drop(['column1','column2',.....])

## Question 4:
Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used 
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [226]:
#open_source=driver4.find_element(By.XPATH,'//header[@class="Header-old header-logged-out js-details-container Details position-relative f4 py-3"]/div/div[2]/div/nav/ul/li[3]/button')
#open_source.click()

driver4=webdriver.Chrome()
driver4.get('https://github.com/')
trending=driver4.find_element(By.XPATH,'//ul[@class="d-lg-flex list-style-none"]/li[3]/div/div[3]/ul/li[2]/a')
trending_url=trending.get_attribute('href')
driver4.get(trending_url)

In [227]:

repo_urls=[]
repositories=driver4.find_elements(By.XPATH,'//div[@class="position-relative container-lg p-responsive pt-6"]/div/div[2]/article/h2/a')
for url in repositories:
    href=url.get_attribute('href')
    repo_urls.append(href)
    
repo_urls

['https://github.com/LazyVim/LazyVim',
 'https://github.com/karpathy/nanoGPT',
 'https://github.com/coollabsio/coolify',
 'https://github.com/xenova/transformers.js',
 'https://github.com/piku/piku',
 'https://github.com/codecrafters-io/build-your-own-x',
 'https://github.com/openai/gpt-2',
 'https://github.com/blakeblackshear/frigate',
 'https://github.com/nvm-sh/nvm',
 'https://github.com/poteto/hiring-without-whiteboards',
 'https://github.com/jackyzha0/quartz',
 'https://github.com/aws/amazon-sagemaker-examples',
 'https://github.com/litestar-org/litestar',
 'https://github.com/paul-gauthier/aider',
 'https://github.com/python-poetry/poetry',
 'https://github.com/tailwindlabs/tailwindcss',
 'https://github.com/lllyasviel/stable-diffusion-webui-forge',
 'https://github.com/EricLBuehler/mistral.rs']

In [228]:
title.clear()
description.clear()
contributors.clear()
languages.clear()

In [231]:
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
import numpy as np

title = []
description = []
contributors = []
languages = []


for url in repo_urls:
    driver4.get(url)
    
    # Extracting Titles
    try:
        title1 = driver4.find_element(By.XPATH, '//div[@class="d-flex flex-wrap flex-justify-end mb-3  px-3 px-md-4 px-lg-5"]/div/div/span[1]')
        title2 = driver4.find_element(By.XPATH, '//div[@class="d-flex flex-wrap flex-justify-end mb-3  px-3 px-md-4 px-lg-5"]/div/div/strong')
        title.append(title1.text + '/' + title2.text)  # Concatenating titles
    except NoSuchElementException:
        title.append('Title not found')

    # Extracting Description
    try:
        #WebDriverWait(driver4,20).until(EC.presence_of_all_elements_located((By.XPATH, '//div[contains(@class,"d-block d-md-none mb-2 px-3 px-md-4 px-lg-5")]/p')))
        desc=driver4.find_element(By.XPATH,'//div[@class="Box-sc-g0xbh4-0 bJMeLZ js-snippet-clipboard-copy-unpositioned"]/article/p[1]')
        description.append(desc.text)
    except NoSuchElementException:
        description.append('-')

    # Extracting Contributors
    try:
        #WebDriverWait(driver4,20).until(EC.presence_of_all_elements_located((By.XPATH, "//span[contains(@class,'Counter ml-1')]")))
        con=driver4.find_element(By.XPATH,'//div[@class="Layout-sidebar"]/div/div[4]/div/h2/a/span')
        contributors.append(con.text)
    except NoSuchElementException:
        contributors.append('-')

    # Extracting Languages
    
    try:
        lang = driver4.find_elements(By.XPATH, "//span[contains(@class,'color-fg-default text-bold mr-1')]")
        for lan in lang:
            lang_section.append(languages.append(lan.text))
    except NoSuchElementException:
        languages.append('None')

# Display the collected data
print("Titles:", title)
print("Descriptions:", description)
print("Contributors:", contributors)
print("Languages:", languages)

Titles: ['LazyVim/LazyVim', 'karpathy/nanoGPT', 'coollabsio/coolify', 'xenova/transformers.js', 'piku/piku', 'codecrafters-io/build-your-own-x', 'openai/gpt-2', 'blakeblackshear/frigate', 'nvm-sh/nvm', 'poteto/hiring-without-whiteboards', 'jackyzha0/quartz', 'aws/amazon-sagemaker-examples', 'litestar-org/litestar', 'paul-gauthier/aider', 'python-poetry/poetry', 'tailwindlabs/tailwindcss', 'lllyasviel/stable-diffusion-webui-forge', 'EricLBuehler/mistral.rs']
Descriptions: ['LazyVim is a Neovim setup powered by 💤 lazy.nvim to make it easy to customize and extend your config. Rather than having to choose between starting from scratch or using a pre-made distro, LazyVim offers the best of both worlds - the flexibility to tweak your config as needed, along with the convenience of a pre-configured setup.', '', '', '', '', '', 'Status: Archive (code is provided as-is, no updates expected)', '', 'nvm allows you to quickly install and use different versions of node via the command line.', 'A list of companies (or teams) that don\'t do "whiteboard" interviews. "Whiteboards" is used as a metaphor, and is a symbol for the kinds of CS trivia questions that are associated with bad interview practices. Whiteboards are not bad – CS trivia questions are. Using sites like HackerRank/LeetCode probably fall into a similar category.', 'Quartz is a set of tools that helps you publish your digital garden and notes as a website for free. Quartz v4 features a from-the-ground rewrite focusing on end-user extensibility and ease-of-use.', '', '', 'Aider lets you pair program with LLMs, to edit code in your local git repository. Start a new project or work with an existing git repo. Aider works best with GPT-4o and Claude 3 Opus and can connect to almost any LLM.', '', '', 'Stable Diffusion WebUI Forge is a platform on top of Stable Diffusion WebUI (based on Gradio) to make development easier, optimize resource management, speed up inference, and study experimental features.', '| Rust Documentation | Python Documentation | Discord |']
Contributors: ['196', '-', '3', '', '', '-', '-', '1', '-', '-', '1', '-', '574', '-', '553', '', '-', '-']
Languages: ['Lua', 'Python', 'PHP', 'Blade', 'Vue', 'Shell', 'Dockerfile', 'CSS', 'JavaScript', 'JavaScript', 'Python', 'Python', 'Shell', 'Makefile', 'Python', 'Python', 'TypeScript', 'CSS', 'C++', 'Shell', 'Dockerfile', 'Other', 'Shell', 'Makefile', 'Other', 'JavaScript', 'TypeScript', 'SCSS', 'JavaScript', 'Dockerfile', 'Jupyter Notebook', 'Python', 'Roff', 'Shell', 'Dockerfile', 'HTML', 'Python', 'Makefile', 'HTML', 'CSS', 'JavaScript', 'Lua', 'Python', 'Scheme', 'HTML', 'Shell', 'SCSS', 'Dockerfile', 'Python', 'HTML', 'TypeScript', 'Rust', 'CSS', 'Other', 'Python', 'JavaScript', 'Cuda', 'C++', 'CSS', 'HTML', 'Other', 'Rust', 'Python', 'Dockerfile']

In [232]:
print("Lenth Titles = ",len(title),"Length Descriptions = ",len(description),"Length Contributors = ",len(contributors),"Length Languages = ",len(languages))

Lenth Titles =  18 Length Descriptions =  18 Length Contributors =  18 Length Languages =  64

In [233]:
for i, (t, c) in enumerate(zip(title, contributors)):
    print(f"{i} : {t} : {c}")

0 : LazyVim/LazyVim : 196
1 : karpathy/nanoGPT : -
2 : coollabsio/coolify : 3
3 : xenova/transformers.js :
4 : piku/piku :
5 : codecrafters-io/build-your-own-x : -
6 : openai/gpt-2 : -
7 : blakeblackshear/frigate : 1
8 : nvm-sh/nvm : -
9 : poteto/hiring-without-whiteboards : -
10 : jackyzha0/quartz : 1
11 : aws/amazon-sagemaker-examples : -
12 : litestar-org/litestar : 574
13 : paul-gauthier/aider : -
14 : python-poetry/poetry : 553
15 : tailwindlabs/tailwindcss :
16 : lllyasviel/stable-diffusion-webui-forge : -
17 : EricLBuehler/mistral.rs : -

In [235]:
description #//p[@class="f4 mb-3 "]

['LazyVim is a Neovim setup powered by 💤 lazy.nvim to make it easy to customize and extend your config. Rather than having to choose between starting from scratch or using a pre-made distro, LazyVim offers the best of both worlds - the flexibility to tweak your config as needed, along with the convenience of a pre-configured setup.',
 '',
 '',
 '',
 '',
 '',
 'Status: Archive (code is provided as-is, no updates expected)',
 '',
 'nvm allows you to quickly install and use different versions of node via the command line.',
 'A list of companies (or teams) that don\'t do "whiteboard" interviews. "Whiteboards" is used as a metaphor, and is a symbol for the kinds of CS trivia questions that are associated with bad interview practices. Whiteboards are not bad – CS trivia questions are. Using sites like HackerRank/LeetCode probably fall into a similar category.',
 'Quartz is a set of tools that helps you publish your digital garden and notes as a website for free. Quartz v4 features a from-the-ground rewrite focusing on end-user extensibility and ease-of-use.',
 '',
 '',
 'Aider lets you pair program with LLMs, to edit code in your local git repository. Start a new project or work with an existing git repo. Aider works best with GPT-4o and Claude 3 Opus and can connect to almost any LLM.',
 '',
 '',
 'Stable Diffusion WebUI Forge is a platform on top of Stable Diffusion WebUI (based on Gradio) to make development easier, optimize resource management, speed up inference, and study experimental features.',
 '| Rust Documentation | Python Documentation | Discord |']

## Question:5
Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the
following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [236]:
driver5=webdriver.Chrome()
driver5.get('https:/www.billboard.com/')

In [237]:
top100=driver5.find_element(By.XPATH,'//li[@class="o-nav__list-item "]/a')
top_href=top100.get_attribute('href')
driver5.get(top_href)

In [238]:
chart_body=[]
hot100=driver5.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in hot100:
    chart_body.append(i.text)

In [239]:
chart_body

['1\nI Had Some Help\nPost Malone Featuring Morgan Wallen\n1\n1\n4',
 '2\nNEW\nHoudini\nEminem\n-\n2\n1',
 '3\nMillion Dollar Baby\nTommy Richman\n3\n2\n6',
 '4\nA Bar Song (Tipsy)\nShaboozey\n4\n3\n8',
 '5\nNot Like Us\nKendrick Lamar\n2\n1\n5',
 '6\nEspresso\nSabrina Carpenter\n5\n4\n8',
 '7\nToo Sweet\nHozier\n8\n1\n11',
 '8\nLose Control\nTeddy Swims\n7\n1\n43',
 '9\nBeautiful Things\nBenson Boone\n9\n2\n20',
 '10\nPink Skies\nZach Bryan\n6\n6\n2',
 '11\nBirds Of A Feather\nBillie Eilish\n12\n11\n3',
 '12\nFortnight\nTaylor Swift Featuring Post Malone\n11\n1\n7',
 '13\nLunch\nBillie Eilish\n10\n5\n3',
 '14\nLike That\nFuture, Metro Boomin & Kendrick Lamar\n13\n1\n11',
 '15\nWanna Be\nGloRilla & Megan Thee Stallion\n39\n11\n9',
 '16\nSaturn\nSZA\n14\n6\n15',
 "17\nWe Can't Be Friends (Wait For Your Love)\nAriana Grande\n15\n1\n13",
 '18\nBAND4BAND\nCentral Cee & Lil Baby\n22\n18\n2',
 '19\nCowgirls\nMorgan Wallen Featuring ERNEST\n20\n19\n25',
 '20\nAustin\nDasha\n25\n20\n13',
 '21\nChihiro\nBillie Eilish\n16\n12\n3',
 '22\nLovin On Me\nJack Harlow\n19\n1\n30',
 '23\nI Remember Everything\nZach Bryan Featuring Kacey Musgraves\n18\n1\n41',
 '24\nMiles On It\nMarshmello & Kane Brown\n21\n21\n5',
 '25\nStick Season\nNoah Kahan\n17\n9\n36',
 '26\nGood Luck, Babe!\nChappell Roan\n31\n26\n9',
 '27\nFeather\nSabrina Carpenter\n26\n21\n27',
 '28\nYeah Glo!\nGloRilla\n28\n28\n17',
 "29\nAin't No Love In Oklahoma\nLuke Combs\n29\n23\n3",
 '30\nGet It Sexyy\nSexyy Red\n24\n20\n12',
 '31\nOne Of Wun\nGunna\n45\n26\n4',
 '32\nWildflower\nBillie Eilish\n27\n17\n3',
 '33\nEuphoria\nKendrick Lamar\n23\n3\n6',
 '34\nI Can Do It With A Broken Heart\nTaylor Swift\n30\n3\n7',
 '35\nEnd Of Beginning\nDjo\n37\n11\n16',
 '36\nI Like The Way You Kiss Me\nArtemas\n36\n12\n11',
 '37\nType Shit\nFuture, Metro Boomin, Travis Scott & Playboi Carti\n38\n2\n11',
 '38\nGreedy\nTate McRae\n35\n3\n38',
 '39\nGata Only\nFloyyMenor X Cris Mj\n32\n27\n12',
 '40\nSlow It Down\nBenson Boone\n43\n40\n11',
 '41\nStargazing\nMyles Smith\n51\n41\n4',
 '42\nAgora Hills\nDoja Cat\n42\n7\n37',
 '43\nWhere It Ends\nBailey Zimmerman\n33\n32\n23',
 '44\nBulletproof\nNate Smith\n40\n40\n9',
 '45\nWhatever She Wants\nBryson Tiller\n46\n19\n16',
 '46\nDown Bad\nTaylor Swift\n41\n2\n7',
 "47\nL'amour De Ma Vie\nBillie Eilish\n34\n22\n3",
 '48\nHalfway To Hell\nJelly Roll\n57\n48\n9',
 '49\nU My Everything\nSexyy Red & Drake\n44\n44\n2',
 '50\nSweet Dreams\nKoe Wetzel\n52\n47\n3',
 "51\nThink I'm In Love With You\nChris Stapleton\n49\n49\n5",
 '52\nBlue\nBillie Eilish\n47\n25\n3',
 '53\nSi No Quieres No\nLuis R Conriquez x Neton Vega\n63\n53\n5',
 '54\nMade For Me\nMuni Long\n55\n20\n21',
 '55\nDirt Cheap\nCody Johnson\n61\n55\n7',
 '56\nFE!N\nTravis Scott Featuring Playboi Carti\n60\n5\n31',
 '57\nWild Ones\nJessie Murph & Jelly Roll\n54\n35\n35',
 "58\nWho's Afraid Of Little Old Me?\nTaylor Swift\n58\n9\n7",
 '59\nIllusion\nDua Lipa\n75\n43\n8',
 '60\nScared To Start\nMichael Marcagi\n70\n54\n16',
 '61\nWe Ride\nBryan Martin\n69\n61\n9',
 '62\nThe Greatest\nBillie Eilish\n50\n24\n3',
 '63\nGuilty As Sin?\nTaylor Swift\n64\n10\n7',
 '64\nEnough (Miami)\nCardi B\n74\n9\n12',
 "65\nTexas Hold 'Em\nBeyonce\n48\n1\n17",
 '66\nBut Daddy I Love Him\nTaylor Swift\n65\n7\n7',
 '67\nObsessed\nOlivia Rodrigo\n66\n14\n11',
 '68\nSkinny\nBillie Eilish\n53\n18\n3',
 '69\nFamily Matters\nDrake\n59\n7\n5',
 '70\nSo Long, London\nTaylor Swift\n68\n5\n7',
 '71\nMy Boy Only Breaks His Favorite Toys\nTaylor Swift\n71\n6\n7',
 '72\nCarnival\n¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti\n67\n1\n17',
 '73\nThe Diner\nBillie Eilish\n62\n31\n3',
 '74\nBelong Together\nMark Ambor\n82\n74\n6',
 '75\nNEW\nRed Wine Supernova\nChappell Roan\n-\n75\n1',
 '76\nWondering Why\nThe Red Clay Strays\n87\n71\n12',
 '77\nHell N Back\nBakar Featuring Summer Walker\n81\n53\n9',
 '78\nTake Her Home\nKenny Chesney\n85\n78\n4',
 "79\nWind Up Missin' You\nTucker Wetmore\n78\n75\n10",
 '80\nNEW\nHot To Go!\nChappell Roan\n-\n80\n1',
 '81\nGet In With Me\nBossMan DLow\n76\n49\n18',
 '82\nSi No Es Contigo\nCris Mj\n72\n72\n2',
 '83\nThe Smallest Man Who Ever Lived\nTaylor Swift\n79\n14\n7',
 '84\nFlorida!!!\nTaylor Swift Featuring Florence + The Machine\n77\n8\n7',
 '85\nAfter Hours\nKehlani\n84\n84\n2',
 '86\nThe Tortured Poets Department\nTaylor Swift\n80\n4\n7',
 '87\nYour Place\nAshley Cooke\n95\n87\n2',
 '88\nOn One Tonight\nGunna\n99\n54\n4',
 '89\nBittersuite\nBillie Eilish\n73\n36\n3',
 '90\nNEW\nNasty\nTinashe\n-\n90\n1',
 '91\nTucson Too Late\nJordan Davis\n88\n71\n14',
 '92\nBack Then Right Now\nTyler Hubbard\n86\n62\n12',
 '93\nOutskirts\nSam Hunt\n94\n66\n13',
 '94\nNEW\nThe Door\nTeddy Swims\n-\n94\n1',
 '95\nRE- ENTRY\nSpin You Around (1/24)\nMorgan Wallen\n-\n24\n18',
 '96\nWine Into Whiskey\nTucker Wetmore\n90\n77\n11',
 '97\nHeat Stick\nShoreline Mafia Presents OhGeesy & Fenix Flexin\n97\n97\n3',
 '98\nNEW\nLet Your Boys Be Country\nJason Aldean\n-\n98\n1',
 '99\nTu Name\nFuerza Regida\n100\n66\n14',
 '100\nloml\nTaylor Swift\n92\n12\n7']

In [240]:
len(chart_body)

100

In [242]:
split_chart_body = []

# Iterate over each element in chart_body and split using regex
for element in chart_body:
    split_elements = re.split(r'\n', element)
    split_chart_body.append(split_elements)

# Print the results
for item in split_chart_body:
    print(item)

['1', 'I Had Some Help', 'Post Malone Featuring Morgan Wallen', '1', '1', '4']
['2', 'NEW', 'Houdini', 'Eminem', '-', '2', '1']
['3', 'Million Dollar Baby', 'Tommy Richman', '3', '2', '6']
['4', 'A Bar Song (Tipsy)', 'Shaboozey', '4', '3', '8']
['5', 'Not Like Us', 'Kendrick Lamar', '2', '1', '5']
['6', 'Espresso', 'Sabrina Carpenter', '5', '4', '8']
['7', 'Too Sweet', 'Hozier', '8', '1', '11']
['8', 'Lose Control', 'Teddy Swims', '7', '1', '43']
['9', 'Beautiful Things', 'Benson Boone', '9', '2', '20']
['10', 'Pink Skies', 'Zach Bryan', '6', '6', '2']
['11', 'Birds Of A Feather', 'Billie Eilish', '12', '11', '3']
['12', 'Fortnight', 'Taylor Swift Featuring Post Malone', '11', '1', '7']
['13', 'Lunch', 'Billie Eilish', '10', '5', '3']
['14', 'Like That', 'Future, Metro Boomin & Kendrick Lamar', '13', '1', '11']
['15', 'Wanna Be', 'GloRilla & Megan Thee Stallion', '39', '11', '9']
['16', 'Saturn', 'SZA', '14', '6', '15']
['17', "We Can't Be Friends (Wait For Your Love)", 'Ariana Grande', '15', '1', '13']
['18', 'BAND4BAND', 'Central Cee & Lil Baby', '22', '18', '2']
['19', 'Cowgirls', 'Morgan Wallen Featuring ERNEST', '20', '19', '25']
['20', 'Austin', 'Dasha', '25', '20', '13']
['21', 'Chihiro', 'Billie Eilish', '16', '12', '3']
['22', 'Lovin On Me', 'Jack Harlow', '19', '1', '30']
['23', 'I Remember Everything', 'Zach Bryan Featuring Kacey Musgraves', '18', '1', '41']
['24', 'Miles On It', 'Marshmello & Kane Brown', '21', '21', '5']
['25', 'Stick Season', 'Noah Kahan', '17', '9', '36']
['26', 'Good Luck, Babe!', 'Chappell Roan', '31', '26', '9']
['27', 'Feather', 'Sabrina Carpenter', '26', '21', '27']
['28', 'Yeah Glo!', 'GloRilla', '28', '28', '17']
['29', "Ain't No Love In Oklahoma", 'Luke Combs', '29', '23', '3']
['30', 'Get It Sexyy', 'Sexyy Red', '24', '20', '12']
['31', 'One Of Wun', 'Gunna', '45', '26', '4']
['32', 'Wildflower', 'Billie Eilish', '27', '17', '3']
['33', 'Euphoria', 'Kendrick Lamar', '23', '3', '6']
['34', 'I Can Do It With A Broken Heart', 'Taylor Swift', '30', '3', '7']
['35', 'End Of Beginning', 'Djo', '37', '11', '16']
['36', 'I Like The Way You Kiss Me', 'Artemas', '36', '12', '11']
['37', 'Type Shit', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '38', '2', '11']
['38', 'Greedy', 'Tate McRae', '35', '3', '38']
['39', 'Gata Only', 'FloyyMenor X Cris Mj', '32', '27', '12']
['40', 'Slow It Down', 'Benson Boone', '43', '40', '11']
['41', 'Stargazing', 'Myles Smith', '51', '41', '4']
['42', 'Agora Hills', 'Doja Cat', '42', '7', '37']
['43', 'Where It Ends', 'Bailey Zimmerman', '33', '32', '23']
['44', 'Bulletproof', 'Nate Smith', '40', '40', '9']
['45', 'Whatever She Wants', 'Bryson Tiller', '46', '19', '16']
['46', 'Down Bad', 'Taylor Swift', '41', '2', '7']
['47', "L'amour De Ma Vie", 'Billie Eilish', '34', '22', '3']
['48', 'Halfway To Hell', 'Jelly Roll', '57', '48', '9']
['49', 'U My Everything', 'Sexyy Red & Drake', '44', '44', '2']
['50', 'Sweet Dreams', 'Koe Wetzel', '52', '47', '3']
['51', "Think I'm In Love With You", 'Chris Stapleton', '49', '49', '5']
['52', 'Blue', 'Billie Eilish', '47', '25', '3']
['53', 'Si No Quieres No', 'Luis R Conriquez x Neton Vega', '63', '53', '5']
['54', 'Made For Me', 'Muni Long', '55', '20', '21']
['55', 'Dirt Cheap', 'Cody Johnson', '61', '55', '7']
['56', 'FE!N', 'Travis Scott Featuring Playboi Carti', '60', '5', '31']
['57', 'Wild Ones', 'Jessie Murph & Jelly Roll', '54', '35', '35']
['58', "Who's Afraid Of Little Old Me?", 'Taylor Swift', '58', '9', '7']
['59', 'Illusion', 'Dua Lipa', '75', '43', '8']
['60', 'Scared To Start', 'Michael Marcagi', '70', '54', '16']
['61', 'We Ride', 'Bryan Martin', '69', '61', '9']
['62', 'The Greatest', 'Billie Eilish', '50', '24', '3']
['63', 'Guilty As Sin?', 'Taylor Swift', '64', '10', '7']
['64', 'Enough (Miami)', 'Cardi B', '74', '9', '12']
['65', "Texas Hold 'Em", 'Beyonce', '48', '1', '17']
['66', 'But Daddy I Love Him', 'Taylor Swift', '65', '7', '7']
['67', 'Obsessed', 'Olivia Rodrigo', '66', '14', '11']
['68', 'Skinny', 'Billie Eilish', '53', '18', '3']
['69', 'Family Matters', 'Drake', '59', '7', '5']
['70', 'So Long, London', 'Taylor Swift', '68', '5', '7']
['71', 'My Boy Only Breaks His Favorite Toys', 'Taylor Swift', '71', '6', '7']
['72', 'Carnival', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '67', '1', '17']
['73', 'The Diner', 'Billie Eilish', '62', '31', '3']
['74', 'Belong Together', 'Mark Ambor', '82', '74', '6']
['75', 'NEW', 'Red Wine Supernova', 'Chappell Roan', '-', '75', '1']
['76', 'Wondering Why', 'The Red Clay Strays', '87', '71', '12']
['77', 'Hell N Back', 'Bakar Featuring Summer Walker', '81', '53', '9']
['78', 'Take Her Home', 'Kenny Chesney', '85', '78', '4']
['79', "Wind Up Missin' You", 'Tucker Wetmore', '78', '75', '10']
['80', 'NEW', 'Hot To Go!', 'Chappell Roan', '-', '80', '1']
['81', 'Get In With Me', 'BossMan DLow', '76', '49', '18']
['82', 'Si No Es Contigo', 'Cris Mj', '72', '72', '2']
['83', 'The Smallest Man Who Ever Lived', 'Taylor Swift', '79', '14', '7']
['84', 'Florida!!!', 'Taylor Swift Featuring Florence + The Machine', '77', '8', '7']
['85', 'After Hours', 'Kehlani', '84', '84', '2']
['86', 'The Tortured Poets Department', 'Taylor Swift', '80', '4', '7']
['87', 'Your Place', 'Ashley Cooke', '95', '87', '2']
['88', 'On One Tonight', 'Gunna', '99', '54', '4']
['89', 'Bittersuite', 'Billie Eilish', '73', '36', '3']
['90', 'NEW', 'Nasty', 'Tinashe', '-', '90', '1']
['91', 'Tucson Too Late', 'Jordan Davis', '88', '71', '14']
['92', 'Back Then Right Now', 'Tyler Hubbard', '86', '62', '12']
['93', 'Outskirts', 'Sam Hunt', '94', '66', '13']
['94', 'NEW', 'The Door', 'Teddy Swims', '-', '94', '1']
['95', 'RE- ENTRY', 'Spin You Around (1/24)', 'Morgan Wallen', '-', '24', '18']
['96', 'Wine Into Whiskey', 'Tucker Wetmore', '90', '77', '11']
['97', 'Heat Stick', 'Shoreline Mafia Presents OhGeesy & Fenix Flexin', '97', '97', '3']
['98', 'NEW', 'Let Your Boys Be Country', 'Jason Aldean', '-', '98', '1']
['99', 'Tu Name', 'Fuerza Regida', '100', '66', '14']
['100', 'loml', 'Taylor Swift', '92', '12', '7']

In [243]:
len(split_chart_body)

100

In [259]:
for entry in split_chart_body:
    if entry[1] in ['NEW', 'RE- ENTRY']:
        del entry[1]

# Print the cleaned chart body
for entry in split_chart_body:
    print(entry)

['1', 'I Had Some Help', 'Post Malone Featuring Morgan Wallen', '1', '1', '4']
['2', 'Houdini', 'Eminem', '-', '2', '1']
['3', 'Million Dollar Baby', 'Tommy Richman', '3', '2', '6']
['4', 'A Bar Song (Tipsy)', 'Shaboozey', '4', '3', '8']
['5', 'Not Like Us', 'Kendrick Lamar', '2', '1', '5']
['6', 'Espresso', 'Sabrina Carpenter', '5', '4', '8']
['7', 'Too Sweet', 'Hozier', '8', '1', '11']
['8', 'Lose Control', 'Teddy Swims', '7', '1', '43']
['9', 'Beautiful Things', 'Benson Boone', '9', '2', '20']
['10', 'Pink Skies', 'Zach Bryan', '6', '6', '2']
['11', 'Birds Of A Feather', 'Billie Eilish', '12', '11', '3']
['12', 'Fortnight', 'Taylor Swift Featuring Post Malone', '11', '1', '7']
['13', 'Lunch', 'Billie Eilish', '10', '5', '3']
['14', 'Like That', 'Future, Metro Boomin & Kendrick Lamar', '13', '1', '11']
['15', 'Wanna Be', 'GloRilla & Megan Thee Stallion', '39', '11', '9']
['16', 'Saturn', 'SZA', '14', '6', '15']
['17', "We Can't Be Friends (Wait For Your Love)", 'Ariana Grande', '15', '1', '13']
['18', 'BAND4BAND', 'Central Cee & Lil Baby', '22', '18', '2']
['19', 'Cowgirls', 'Morgan Wallen Featuring ERNEST', '20', '19', '25']
['20', 'Austin', 'Dasha', '25', '20', '13']
['21', 'Chihiro', 'Billie Eilish', '16', '12', '3']
['22', 'Lovin On Me', 'Jack Harlow', '19', '1', '30']
['23', 'I Remember Everything', 'Zach Bryan Featuring Kacey Musgraves', '18', '1', '41']
['24', 'Miles On It', 'Marshmello & Kane Brown', '21', '21', '5']
['25', 'Stick Season', 'Noah Kahan', '17', '9', '36']
['26', 'Good Luck, Babe!', 'Chappell Roan', '31', '26', '9']
['27', 'Feather', 'Sabrina Carpenter', '26', '21', '27']
['28', 'Yeah Glo!', 'GloRilla', '28', '28', '17']
['29', "Ain't No Love In Oklahoma", 'Luke Combs', '29', '23', '3']
['30', 'Get It Sexyy', 'Sexyy Red', '24', '20', '12']
['31', 'One Of Wun', 'Gunna', '45', '26', '4']
['32', 'Wildflower', 'Billie Eilish', '27', '17', '3']
['33', 'Euphoria', 'Kendrick Lamar', '23', '3', '6']
['34', 'I Can Do It With A Broken Heart', 'Taylor Swift', '30', '3', '7']
['35', 'End Of Beginning', 'Djo', '37', '11', '16']
['36', 'I Like The Way You Kiss Me', 'Artemas', '36', '12', '11']
['37', 'Type Shit', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '38', '2', '11']
['38', 'Greedy', 'Tate McRae', '35', '3', '38']
['39', 'Gata Only', 'FloyyMenor X Cris Mj', '32', '27', '12']
['40', 'Slow It Down', 'Benson Boone', '43', '40', '11']
['41', 'Stargazing', 'Myles Smith', '51', '41', '4']
['42', 'Agora Hills', 'Doja Cat', '42', '7', '37']
['43', 'Where It Ends', 'Bailey Zimmerman', '33', '32', '23']
['44', 'Bulletproof', 'Nate Smith', '40', '40', '9']
['45', 'Whatever She Wants', 'Bryson Tiller', '46', '19', '16']
['46', 'Down Bad', 'Taylor Swift', '41', '2', '7']
['47', "L'amour De Ma Vie", 'Billie Eilish', '34', '22', '3']
['48', 'Halfway To Hell', 'Jelly Roll', '57', '48', '9']
['49', 'U My Everything', 'Sexyy Red & Drake', '44', '44', '2']
['50', 'Sweet Dreams', 'Koe Wetzel', '52', '47', '3']
['51', "Think I'm In Love With You", 'Chris Stapleton', '49', '49', '5']
['52', 'Blue', 'Billie Eilish', '47', '25', '3']
['53', 'Si No Quieres No', 'Luis R Conriquez x Neton Vega', '63', '53', '5']
['54', 'Made For Me', 'Muni Long', '55', '20', '21']
['55', 'Dirt Cheap', 'Cody Johnson', '61', '55', '7']
['56', 'FE!N', 'Travis Scott Featuring Playboi Carti', '60', '5', '31']
['57', 'Wild Ones', 'Jessie Murph & Jelly Roll', '54', '35', '35']
['58', "Who's Afraid Of Little Old Me?", 'Taylor Swift', '58', '9', '7']
['59', 'Illusion', 'Dua Lipa', '75', '43', '8']
['60', 'Scared To Start', 'Michael Marcagi', '70', '54', '16']
['61', 'We Ride', 'Bryan Martin', '69', '61', '9']
['62', 'The Greatest', 'Billie Eilish', '50', '24', '3']
['63', 'Guilty As Sin?', 'Taylor Swift', '64', '10', '7']
['64', 'Enough (Miami)', 'Cardi B', '74', '9', '12']
['65', "Texas Hold 'Em", 'Beyonce', '48', '1', '17']
['66', 'But Daddy I Love Him', 'Taylor Swift', '65', '7', '7']
['67', 'Obsessed', 'Olivia Rodrigo', '66', '14', '11']
['68', 'Skinny', 'Billie Eilish', '53', '18', '3']
['69', 'Family Matters', 'Drake', '59', '7', '5']
['70', 'So Long, London', 'Taylor Swift', '68', '5', '7']
['71', 'My Boy Only Breaks His Favorite Toys', 'Taylor Swift', '71', '6', '7']
['72', 'Carnival', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '67', '1', '17']
['73', 'The Diner', 'Billie Eilish', '62', '31', '3']
['74', 'Belong Together', 'Mark Ambor', '82', '74', '6']
['75', 'Red Wine Supernova', 'Chappell Roan', '-', '75', '1']
['76', 'Wondering Why', 'The Red Clay Strays', '87', '71', '12']
['77', 'Hell N Back', 'Bakar Featuring Summer Walker', '81', '53', '9']
['78', 'Take Her Home', 'Kenny Chesney', '85', '78', '4']
['79', "Wind Up Missin' You", 'Tucker Wetmore', '78', '75', '10']
['80', 'Hot To Go!', 'Chappell Roan', '-', '80', '1']
['81', 'Get In With Me', 'BossMan DLow', '76', '49', '18']
['82', 'Si No Es Contigo', 'Cris Mj', '72', '72', '2']
['83', 'The Smallest Man Who Ever Lived', 'Taylor Swift', '79', '14', '7']
['84', 'Florida!!!', 'Taylor Swift Featuring Florence + The Machine', '77', '8', '7']
['85', 'After Hours', 'Kehlani', '84', '84', '2']
['86', 'The Tortured Poets Department', 'Taylor Swift', '80', '4', '7']
['87', 'Your Place', 'Ashley Cooke', '95', '87', '2']
['88', 'On One Tonight', 'Gunna', '99', '54', '4']
['89', 'Bittersuite', 'Billie Eilish', '73', '36', '3']
['90', 'Nasty', 'Tinashe', '-', '90', '1']
['91', 'Tucson Too Late', 'Jordan Davis', '88', '71', '14']
['92', 'Back Then Right Now', 'Tyler Hubbard', '86', '62', '12']
['93', 'Outskirts', 'Sam Hunt', '94', '66', '13']
['94', 'The Door', 'Teddy Swims', '-', '94', '1']
['95', 'Spin You Around (1/24)', 'Morgan Wallen', '-', '24', '18']
['96', 'Wine Into Whiskey', 'Tucker Wetmore', '90', '77', '11']
['97', 'Heat Stick', 'Shoreline Mafia Presents OhGeesy & Fenix Flexin', '97', '97', '3']
['98', 'Let Your Boys Be Country', 'Jason Aldean', '-', '98', '1']
['99', 'Tu Name', 'Fuerza Regida', '100', '66', '14']
['100', 'loml', 'Taylor Swift', '92', '12', '7']

In [260]:
chart_col=['Rank','Song Name','Artist Name','Last Week','Peak Position', 'WeeksOnChart']

In [261]:
import pandas as pd
topcharts=pd.DataFrame(data=split_chart_body,columns=chart_col)
topcharts

,Rank,Song Name,Artist Name,Last Week,Peak Position,WeeksOnChart
0,1,I Had Some Help,Post Malone Featuring Morgan Wallen,1,1,4
1,2,Houdini,Eminem,-,2,1
2,3,Million Dollar Baby,Tommy Richman,3,2,6
3,4,A Bar Song (Tipsy),Shaboozey,4,3,8
4,5,Not Like Us,Kendrick Lamar,2,1,5
...,...,...,...,...,...,...
95,96,Wine Into Whiskey,Tucker Wetmore,90,77,11
96,97,Heat Stick,Shoreline Mafia Presents OhGeesy & Fenix Flexin,97,97,3
97,98,Let Your Boys Be Country,Jason Aldean,-,98,1
98,99,Tu Name,Fuerza Regida,100,66,14
99,100,loml,Taylor Swift,92,12,7

## Question 6:
Scrape the details of Highest selling novels.
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre
 Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [270]:
driver6=webdriver.Chrome()
driver6.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [271]:
cols=[]
heads=driver6.find_elements(By.XPATH,'//div[@class="embed block"]/table/thead/tr/th')
for h in heads:
    cols.append(h.text)
cols

['Rank', 'Title', 'Author', 'Volume Sales', 'Publisher', 'Genre']

In [273]:
t_body=[]
novel_rows=driver6.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td')
for row in novel_rows:
    t_body.append(row.text)

In [274]:
t_body

['1',
 'Da Vinci Code,The',
 'Brown, Dan',
 '5,094,805',
 'Transworld',
 'Crime, Thriller & Adventure',
 '2',
 'Harry Potter and the Deathly Hallows',
 'Rowling, J.K.',
 '4,475,152',
 'Bloomsbury',
 "Children's Fiction",
 '3',
 "Harry Potter and the Philosopher's Stone",
 'Rowling, J.K.',
 '4,200,654',
 'Bloomsbury',
 "Children's Fiction",
 '4',
 'Harry Potter and the Order of the Phoenix',
 'Rowling, J.K.',
 '4,179,479',
 'Bloomsbury',
 "Children's Fiction",
 '5',
 'Fifty Shades of Grey',
 'James, E. L.',
 '3,758,936',
 'Random House',
 'Romance & Sagas',
 '6',
 'Harry Potter and the Goblet of Fire',
 'Rowling, J.K.',
 '3,583,215',
 'Bloomsbury',
 "Children's Fiction",
 '7',
 'Harry Potter and the Chamber of Secrets',
 'Rowling, J.K.',
 '3,484,047',
 'Bloomsbury',
 "Children's Fiction",
 '8',
 'Harry Potter and the Prisoner of Azkaban',
 'Rowling, J.K.',
 '3,377,906',
 'Bloomsbury',
 "Children's Fiction",
 '9',
 'Angels and Demons',
 'Brown, Dan',
 '3,193,946',
 'Transworld',
 'Crime, Thriller & Adventure',
 '10',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Rowling, J.K.',
 '2,950,264',
 'Bloomsbury',
 "Children's Fiction",
 '11',
 'Fifty Shades Darker',
 'James, E. L.',
 '2,479,784',
 'Random House',
 'Romance & Sagas',
 '12',
 'Twilight',
 'Meyer, Stephenie',
 '2,315,405',
 'Little, Brown Book',
 'Young Adult Fiction',
 '13',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Larsson, Stieg',
 '2,233,570',
 'Quercus',
 'Crime, Thriller & Adventure',
 '14',
 'Fifty Shades Freed',
 'James, E. L.',
 '2,193,928',
 'Random House',
 'Romance & Sagas',
 '15',
 'Lost Symbol,The',
 'Brown, Dan',
 '2,183,031',
 'Transworld',
 'Crime, Thriller & Adventure',
 '16',
 'New Moon',
 'Meyer, Stephenie',
 '2,152,737',
 'Little, Brown Book',
 'Young Adult Fiction',
 '17',
 'Deception Point',
 'Brown, Dan',
 '2,062,145',
 'Transworld',
 'Crime, Thriller & Adventure',
 '18',
 'Eclipse',
 'Meyer, Stephenie',
 '2,052,876',
 'Little, Brown Book',
 'Young Adult Fiction',
 '19',
 'Lovely Bones,The',
 'Sebold, Alice',
 '2,005,598',
 'Pan Macmillan',
 'General & Literary Fiction',
 '20',
 'Curious Incident of the Dog in the Night-time,The',
 'Haddon, Mark',
 '1,979,552',
 'Random House',
 'General & Literary Fiction',
 '21',
 'Digital Fortress',
 'Brown, Dan',
 '1,928,900',
 'Transworld',
 'Crime, Thriller & Adventure',
 '22',
 'Short History of Nearly Everything,A',
 'Bryson, Bill',
 '1,852,919',
 'Transworld',
 'Popular Science',
 '23',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Larsson, Stieg',
 '1,814,784',
 'Quercus',
 'Crime, Thriller & Adventure',
 '24',
 'Breaking Dawn',
 'Meyer, Stephenie',
 '1,787,118',
 'Little, Brown Book',
 'Young Adult Fiction',
 '25',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Carle, Eric',
 '1,783,535',
 'Penguin',
 'Picture Books',
 '26',
 'Gruffalo,The',
 'Donaldson, Julia',
 '1,781,269',
 'Pan Macmillan',
 'Picture Books',
 '27',
 "Jamie's 30-Minute Meals",
 'Oliver, Jamie',
 '1,743,266',
 'Penguin',
 'Food & Drink: General',
 '28',
 'Kite Runner,The',
 'Hosseini, Khaled',
 '1,629,119',
 'Bloomsbury',
 'General & Literary Fiction',
 '29',
 'One Day',
 'Nicholls, David',
 '1,616,068',
 'Hodder & Stoughton',
 'General & Literary Fiction',
 '30',
 'Thousand Splendid Suns,A',
 'Hosseini, Khaled',
 '1,583,992',
 'Bloomsbury',
 'General & Literary Fiction',
 '31',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 'Larsson, Stieg',
 '1,555,135',
 'Quercus',
 'Crime, Thriller & Adventure',
 '32',
 "Time Traveler's Wife,The",
 'Niffenegger, Audrey',
 '1,546,886',
 'Random House',
 'General & Literary Fiction',
 '33',
 'Atonement',
 'McEwan, Ian',
 '1,539,428',
 'Random House',
 'General & Literary Fiction',
 '34',
 "Bridget Jones's Diary:A Novel",
 'Fielding, Helen',
 '1,508,205',
 'Pan Macmillan',
 'General & Literary Fiction',
 '35',
 'World According to Clarkson,The',
 'Clarkson, Jeremy',
 '1,489,403',
 'Penguin',
 'Humour: Collections & General',
 '36',
 "Captain Corelli's Mandolin",
 'Bernieres, Louis de',
 '1,352,318',
 'Random House',
 'General & Literary Fiction',
 '37',
 'Sound of Laughter,The',
 'Kay, Peter',
 '1,310,207',
 'Random House',
 'Autobiography: General',
 '38',
 'Life of Pi',
 'Martel, Yann',
 '1,310,176',
 'Canongate',
 'General & Literary Fiction',
 '39',
 'Billy Connolly',
 'Stephenson, Pamela',
 '1,231,957',
 'HarperCollins',
 'Biography: The Arts',
 '40',
 'Child Called It,A',
 'Pelzer, Dave',
 '1,217,712',
 'Orion',
 'Autobiography: General',
 '41',
 "Gruffalo's Child,The",
 'Donaldson, Julia',
 '1,208,711',
 'Pan Macmillan',
 'Picture Books',
 '42',
 "Angela's Ashes:A Memoir of a Childhood",
 'McCourt, Frank',
 '1,204,058',
 'HarperCollins',
 'Autobiography: General',
 '43',
 'Birdsong',
 'Faulks, Sebastian',
 '1,184,967',
 'Random House',
 'General & Literary Fiction',
 '44',
 'Northern Lights:His Dark Materials S.',
 'Pullman, Philip',
 '1,181,503',
 'Scholastic Ltd.',
 'Young Adult Fiction',
 '45',
 'Labyrinth',
 'Mosse, Kate',
 '1,181,093',
 'Orion',
 'General & Literary Fiction',
 '46',
 'Harry Potter and the Half-blood Prince',
 'Rowling, J.K.',
 '1,153,181',
 'Bloomsbury',
 'Science Fiction & Fantasy',
 '47',
 'Help,The',
 'Stockett, Kathryn',
 '1,132,336',
 'Penguin',
 'General & Literary Fiction',
 '48',
 'Man and Boy',
 'Parsons, Tony',
 '1,130,802',
 'HarperCollins',
 'General & Literary Fiction',
 '49',
 'Memoirs of a Geisha',
 'Golden, Arthur',
 '1,126,337',
 'Random House',
 'General & Literary Fiction',
 '50',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'McCall Smith, Alexander',
 '1,115,549',
 'Little, Brown Book',
 'Crime, Thriller & Adventure',
 '51',
 'Island,The',
 'Hislop, Victoria',
 '1,108,328',
 'Headline',
 'General & Literary Fiction',
 '52',
 'PS, I Love You',
 'Ahern, Cecelia',
 '1,107,379',
 'HarperCollins',
 'General & Literary Fiction',
 '53',
 'You are What You Eat:The Plan That Will Change Your Life',
 'McKeith, Gillian',
 '1,104,403',
 'Penguin',
 'Fitness & Diet',
 '54',
 'Shadow of the Wind,The',
 'Zafon, Carlos Ruiz',
 '1,092,349',
 'Orion',
 'General & Literary Fiction',
 '55',
 'Tales of Beedle the Bard,The',
 'Rowling, J.K.',
 '1,090,847',
 'Bloomsbury',
 "Children's Fiction",
 '56',
 'Broker,The',
 'Grisham, John',
 '1,087,262',
 'Random House',
 'Crime, Thriller & Adventure',
 '57',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Atkins, Robert C.',
 '1,054,196',
 'Random House',
 'Fitness & Diet',
 '58',
 'Subtle Knife,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,037,160',
 'Scholastic Ltd.',
 'Young Adult Fiction',
 '59',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 'Truss, Lynne',
 '1,023,688',
 'Profile Books Group',
 'Usage & Writing Guides',
 '60',
 "Delia's How to Cook:(Bk.1)",
 'Smith, Delia',
 '1,015,956',
 'Random House',
 'Food & Drink: General',
 '61',
 'Chocolat',
 'Harris, Joanne',
 '1,009,873',
 'Transworld',
 'General & Literary Fiction',
 '62',
 'Boy in the Striped Pyjamas,The',
 'Boyne, John',
 '1,004,414',
 'Random House Childrens Books G',
 'Young Adult Fiction',
 '63',
 "My Sister's Keeper",
 'Picoult, Jodi',
 '1,003,780',
 'Hodder & Stoughton',
 'General & Literary Fiction',
 '64',
 'Amber Spyglass,The:His Dark Materials S.',
 'Pullman, Philip',
 '1,002,314',
 'Scholastic Ltd.',
 'Young Adult Fiction',
 '65',
 'To Kill a Mockingbird',
 'Lee, Harper',
 '998,213',
 'Random House',
 'General & Literary Fiction',
 '66',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Gray, John',
 '992,846',
 'HarperCollins',
 'Popular Culture & Media: General Interest',
 '67',
 'Dear Fatty',
 'French, Dawn',
 '986,753',
 'Random House',
 'Autobiography: The Arts',
 '68',
 'Short History of Tractors in Ukrainian,A',
 'Lewycka, Marina',
 '986,115',
 'Penguin',
 'General & Literary Fiction',
 '69',
 'Hannibal',
 'Harris, Thomas',
 '970,509',
 'Random House',
 'Crime, Thriller & Adventure',
 '70',
 'Lord of the Rings,The',
 'Tolkien, J. R. R.',
 '967,466',
 'HarperCollins',
 'Science Fiction & Fantasy',
 '71',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Moore, Michael',
 '963,353',
 'Penguin',
 'Current Affairs & Issues',
 '72',
 'Interpretation of Murder,The',
 'Rubenfeld, Jed',
 '962,515',
 'Headline',
 'Crime, Thriller & Adventure',
 '73',
 'Sharon Osbourne Extreme:My Autobiography',
 'Osbourne, Sharon',
 '959,496',
 'Little, Brown Book',
 'Autobiography: The Arts',
 '74',
 'Alchemist,The:A Fable About Following Your Dream',
 'Coelho, Paulo',
 '956,114',
 'HarperCollins',
 'General & Literary Fiction',
 '75',
 "At My Mother's Knee ...:and Other Low Joints",
 "O'Grady, Paul",
 '945,640',
 'Transworld',
 'Autobiography: The Arts',
 '76',
 'Notes from a Small Island',
 'Bryson, Bill',
 '931,312',
 'Transworld',
 'Travel Writing',
 '77',
 'Return of the Naked Chef,The',
 'Oliver, Jamie',
 '925,425',
 'Penguin',
 'Food & Drink: General',
 '78',
 'Bridget Jones: The Edge of Reason',
 'Fielding, Helen',
 '924,695',
 'Pan Macmillan',
 'General & Literary Fiction',
 '79',
 "Jamie's Italy",
 'Oliver, Jamie',
 '906,968',
 'Penguin',
 'National & Regional Cuisine',
 '80',
 'I Can Make You Thin',
 'McKenna, Paul',
 '905,086',
 'Transworld',
 'Fitness & Diet',
 '81',
 'Down Under',
 'Bryson, Bill',
 '890,847',
 'Transworld',
 'Travel Writing',
 '82',
 'Summons,The',
 'Grisham, John',
 '869,671',
 'Random House',
 'Crime, Thriller & Adventure',
 '83',
 'Small Island',
 'Levy, Andrea',
 '869,659',
 'Headline',
 'General & Literary Fiction',
 '84',
 'Nigella Express',
 'Lawson, Nigella',
 '862,602',
 'Random House',
 'Food & Drink: General',
 '85',
 'Brick Lane',
 'Ali, Monica',
 '856,540',
 'Transworld',
 'General & Literary Fiction',
 '86',
 "Memory Keeper's Daughter,The",
 'Edwards, Kim',
 '845,858',
 'Penguin',
 'General & Literary Fiction',
 '87',
 'Room on the Broom',
 'Donaldson, Julia',
 '842,535',
 'Pan Macmillan',
 'Picture Books',
 '88',
 'About a Boy',
 'Hornby, Nick',
 '828,215',
 'Penguin',
 'General & Literary Fiction',
 '89',
 'My Booky Wook',
 'Brand, Russell',
 '820,563',
 'Hodder & Stoughton',
 'Autobiography: The Arts',
 '90',
 'God Delusion,The',
 'Dawkins, Richard',
 '816,907',
 'Transworld',
 'Popular Science',
 '91',
 '"Beano" Annual,The',
 '0',
 '816,585',
 'D.C. Thomson',
 "Children's Annuals",
 '92',
 'White Teeth',
 'Smith, Zadie',
 '815,586',
 'Penguin',
 'General & Literary Fiction',
 '93',
 'House at Riverton,The',
 'Morton, Kate',
 '814,370',
 'Pan Macmillan',
 'General & Literary Fiction',
 '94',
 'Book Thief,The',
 'Zusak, Markus',
 '809,641',
 'Transworld',
 'General & Literary Fiction',
 '95',
 'Nights of Rain and Stars',
 'Binchy, Maeve',
 '808,900',
 'Orion',
 'General & Literary Fiction',
 '96',
 'Ghost,The',
 'Harris, Robert',
 '807,311',
 'Random House',
 'General & Literary Fiction',
 '97',
 'Happy Days with the Naked Chef',
 'Oliver, Jamie',
 '794,201',
 'Penguin',
 'Food & Drink: General',
 '98',
 'Hunger Games,The:Hunger Games Trilogy',
 'Collins, Suzanne',
 '792,187',
 'Scholastic Ltd.',
 'Young Adult Fiction',
 '99',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 'Pelzer, Dave',
 '791,507',
 'Orion',
 'Biography: General',
 '100',
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours",
 'Oliver, Jamie',
 '791,095',
 'Penguin',
 'Food & Drink: General']

In [275]:
len(t_body)

600

In [276]:
import numpy as np
novels=np.array(t_body)

In [280]:
novels=novels.reshape(100,6)

In [281]:
novels

array([['1', 'Da Vinci Code,The', 'Brown, Dan', '5,094,805',
        'Transworld', 'Crime, Thriller & Adventure'],
       ['2', 'Harry Potter and the Deathly Hallows', 'Rowling, J.K.',
        '4,475,152', 'Bloomsbury', "Children's Fiction"],
       ['3', "Harry Potter and the Philosopher's Stone", 'Rowling, J.K.',
        '4,200,654', 'Bloomsbury', "Children's Fiction"],
       ['4', 'Harry Potter and the Order of the Phoenix',
        'Rowling, J.K.', '4,179,479', 'Bloomsbury', "Children's Fiction"],
       ['5', 'Fifty Shades of Grey', 'James, E. L.', '3,758,936',
        'Random House', 'Romance & Sagas'],
       ['6', 'Harry Potter and the Goblet of Fire', 'Rowling, J.K.',
        '3,583,215', 'Bloomsbury', "Children's Fiction"],
       ['7', 'Harry Potter and the Chamber of Secrets', 'Rowling, J.K.',
        '3,484,047', 'Bloomsbury', "Children's Fiction"],
       ['8', 'Harry Potter and the Prisoner of Azkaban', 'Rowling, J.K.',
        '3,377,906', 'Bloomsbury', "Children's Fiction"],
       ['9', 'Angels and Demons', 'Brown, Dan', '3,193,946',
        'Transworld', 'Crime, Thriller & Adventure'],
       ['10',
        "Harry Potter and the Half-blood Prince:Children's Edition",
        'Rowling, J.K.', '2,950,264', 'Bloomsbury', "Children's Fiction"],
       ['11', 'Fifty Shades Darker', 'James, E. L.', '2,479,784',
        'Random House', 'Romance & Sagas'],
       ['12', 'Twilight', 'Meyer, Stephenie', '2,315,405',
        'Little, Brown Book', 'Young Adult Fiction'],
       ['13', 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
        'Larsson, Stieg', '2,233,570', 'Quercus',
        'Crime, Thriller & Adventure'],
       ['14', 'Fifty Shades Freed', 'James, E. L.', '2,193,928',
        'Random House', 'Romance & Sagas'],
       ['15', 'Lost Symbol,The', 'Brown, Dan', '2,183,031', 'Transworld',
        'Crime, Thriller & Adventure'],
       ['16', 'New Moon', 'Meyer, Stephenie', '2,152,737',
        'Little, Brown Book', 'Young Adult Fiction'],
       ['17', 'Deception Point', 'Brown, Dan', '2,062,145', 'Transworld',
        'Crime, Thriller & Adventure'],
       ['18', 'Eclipse', 'Meyer, Stephenie', '2,052,876',
        'Little, Brown Book', 'Young Adult Fiction'],
       ['19', 'Lovely Bones,The', 'Sebold, Alice', '2,005,598',
        'Pan Macmillan', 'General & Literary Fiction'],
       ['20', 'Curious Incident of the Dog in the Night-time,The',
        'Haddon, Mark', '1,979,552', 'Random House',
        'General & Literary Fiction'],
       ['21', 'Digital Fortress', 'Brown, Dan', '1,928,900',
        'Transworld', 'Crime, Thriller & Adventure'],
       ['22', 'Short History of Nearly Everything,A', 'Bryson, Bill',
        '1,852,919', 'Transworld', 'Popular Science'],
       ['23', 'Girl Who Played with Fire,The:Millennium Trilogy',
        'Larsson, Stieg', '1,814,784', 'Quercus',
        'Crime, Thriller & Adventure'],
       ['24', 'Breaking Dawn', 'Meyer, Stephenie', '1,787,118',
        'Little, Brown Book', 'Young Adult Fiction'],
       ['25', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
        'Carle, Eric', '1,783,535', 'Penguin', 'Picture Books'],
       ['26', 'Gruffalo,The', 'Donaldson, Julia', '1,781,269',
        'Pan Macmillan', 'Picture Books'],
       ['27', "Jamie's 30-Minute Meals", 'Oliver, Jamie', '1,743,266',
        'Penguin', 'Food & Drink: General'],
       ['28', 'Kite Runner,The', 'Hosseini, Khaled', '1,629,119',
        'Bloomsbury', 'General & Literary Fiction'],
       ['29', 'One Day', 'Nicholls, David', '1,616,068',
        'Hodder & Stoughton', 'General & Literary Fiction'],
       ['30', 'Thousand Splendid Suns,A', 'Hosseini, Khaled',
        '1,583,992', 'Bloomsbury', 'General & Literary Fiction'],
       ['31', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
        'Larsson, Stieg', '1,555,135', 'Quercus',
        'Crime, Thriller & Adventure'],
       ['32', "Time Traveler's Wife,The", 'Niffenegger, Audrey',
        '1,546,886', 'Random House', 'General & Literary Fiction'],
       ['33', 'Atonement', 'McEwan, Ian', '1,539,428', 'Random House',
        'General & Literary Fiction'],
       ['34', "Bridget Jones's Diary:A Novel", 'Fielding, Helen',
        '1,508,205', 'Pan Macmillan', 'General & Literary Fiction'],
       ['35', 'World According to Clarkson,The', 'Clarkson, Jeremy',
        '1,489,403', 'Penguin', 'Humour: Collections & General'],
       ['36', "Captain Corelli's Mandolin", 'Bernieres, Louis de',
        '1,352,318', 'Random House', 'General & Literary Fiction'],
       ['37', 'Sound of Laughter,The', 'Kay, Peter', '1,310,207',
        'Random House', 'Autobiography: General'],
       ['38', 'Life of Pi', 'Martel, Yann', '1,310,176', 'Canongate',
        'General & Literary Fiction'],
       ['39', 'Billy Connolly', 'Stephenson, Pamela', '1,231,957',
        'HarperCollins', 'Biography: The Arts'],
       ['40', 'Child Called It,A', 'Pelzer, Dave', '1,217,712', 'Orion',
        'Autobiography: General'],
       ['41', "Gruffalo's Child,The", 'Donaldson, Julia', '1,208,711',
        'Pan Macmillan', 'Picture Books'],
       ['42', "Angela's Ashes:A Memoir of a Childhood", 'McCourt, Frank',
        '1,204,058', 'HarperCollins', 'Autobiography: General'],
       ['43', 'Birdsong', 'Faulks, Sebastian', '1,184,967',
        'Random House', 'General & Literary Fiction'],
       ['44', 'Northern Lights:His Dark Materials S.', 'Pullman, Philip',
        '1,181,503', 'Scholastic Ltd.', 'Young Adult Fiction'],
       ['45', 'Labyrinth', 'Mosse, Kate', '1,181,093', 'Orion',
        'General & Literary Fiction'],
       ['46', 'Harry Potter and the Half-blood Prince', 'Rowling, J.K.',
        '1,153,181', 'Bloomsbury', 'Science Fiction & Fantasy'],
       ['47', 'Help,The', 'Stockett, Kathryn', '1,132,336', 'Penguin',
        'General & Literary Fiction'],
       ['48', 'Man and Boy', 'Parsons, Tony', '1,130,802',
        'HarperCollins', 'General & Literary Fiction'],
       ['49', 'Memoirs of a Geisha', 'Golden, Arthur', '1,126,337',
        'Random House', 'General & Literary Fiction'],
       ['50',
        "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
        'McCall Smith, Alexander', '1,115,549', 'Little, Brown Book',
        'Crime, Thriller & Adventure'],
       ['51', 'Island,The', 'Hislop, Victoria', '1,108,328', 'Headline',
        'General & Literary Fiction'],
       ['52', 'PS, I Love You', 'Ahern, Cecelia', '1,107,379',
        'HarperCollins', 'General & Literary Fiction'],
       ['53', 'You are What You Eat:The Plan That Will Change Your Life',
        'McKeith, Gillian', '1,104,403', 'Penguin', 'Fitness & Diet'],
       ['54', 'Shadow of the Wind,The', 'Zafon, Carlos Ruiz',
        '1,092,349', 'Orion', 'General & Literary Fiction'],
       ['55', 'Tales of Beedle the Bard,The', 'Rowling, J.K.',
        '1,090,847', 'Bloomsbury', "Children's Fiction"],
       ['56', 'Broker,The', 'Grisham, John', '1,087,262', 'Random House',
        'Crime, Thriller & Adventure'],
       ['57',
        "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
        'Atkins, Robert C.', '1,054,196', 'Random House',
        'Fitness & Diet'],
       ['58', 'Subtle Knife,The:His Dark Materials S.',
        'Pullman, Philip', '1,037,160', 'Scholastic Ltd.',
        'Young Adult Fiction'],
       ['59',
        'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
        'Truss, Lynne', '1,023,688', 'Profile Books Group',
        'Usage & Writing Guides'],
       ['60', "Delia's How to Cook:(Bk.1)", 'Smith, Delia', '1,015,956',
        'Random House', 'Food & Drink: General'],
       ['61', 'Chocolat', 'Harris, Joanne', '1,009,873', 'Transworld',
        'General & Literary Fiction'],
       ['62', 'Boy in the Striped Pyjamas,The', 'Boyne, John',
        '1,004,414', 'Random House Childrens Books G',
        'Young Adult Fiction'],
       ['63', "My Sister's Keeper", 'Picoult, Jodi', '1,003,780',
        'Hodder & Stoughton', 'General & Literary Fiction'],
       ['64', 'Amber Spyglass,The:His Dark Materials S.',
        'Pullman, Philip', '1,002,314', 'Scholastic Ltd.',
        'Young Adult Fiction'],
       ['65', 'To Kill a Mockingbird', 'Lee, Harper', '998,213',
        'Random House', 'General & Literary Fiction'],
       ['66',
        'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
        'Gray, John', '992,846', 'HarperCollins',
        'Popular Culture & Media: General Interest'],
       ['67', 'Dear Fatty', 'French, Dawn', '986,753', 'Random House',
        'Autobiography: The Arts'],
       ['68', 'Short History of Tractors in Ukrainian,A',
        'Lewycka, Marina', '986,115', 'Penguin',
        'General & Literary Fiction'],
       ['69', 'Hannibal', 'Harris, Thomas', '970,509', 'Random House',
        'Crime, Thriller & Adventure'],
       ['70', 'Lord of the Rings,The', 'Tolkien, J. R. R.', '967,466',
        'HarperCollins', 'Science Fiction & Fantasy'],
       ['71',
        'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
        'Moore, Michael', '963,353', 'Penguin',
        'Current Affairs & Issues'],
       ['72', 'Interpretation of Murder,The', 'Rubenfeld, Jed',
        '962,515', 'Headline', 'Crime, Thriller & Adventure'],
       ['73', 'Sharon Osbourne Extreme:My Autobiography',
        'Osbourne, Sharon', '959,496', 'Little, Brown Book',
        'Autobiography: The Arts'],
       ['74', 'Alchemist,The:A Fable About Following Your Dream',
        'Coelho, Paulo', '956,114', 'HarperCollins',
        'General & Literary Fiction'],
       ['75', "At My Mother's Knee ...:and Other Low Joints",
        "O'Grady, Paul", '945,640', 'Transworld',
        'Autobiography: The Arts'],
       ['76', 'Notes from a Small Island', 'Bryson, Bill', '931,312',
        'Transworld', 'Travel Writing'],
       ['77', 'Return of the Naked Chef,The', 'Oliver, Jamie', '925,425',
        'Penguin', 'Food & Drink: General'],
       ['78', 'Bridget Jones: The Edge of Reason', 'Fielding, Helen',
        '924,695', 'Pan Macmillan', 'General & Literary Fiction'],
       ['79', "Jamie's Italy", 'Oliver, Jamie', '906,968', 'Penguin',
        'National & Regional Cuisine'],
       ['80', 'I Can Make You Thin', 'McKenna, Paul', '905,086',
        'Transworld', 'Fitness & Diet'],
       ['81', 'Down Under', 'Bryson, Bill', '890,847', 'Transworld',
        'Travel Writing'],
       ['82', 'Summons,The', 'Grisham, John', '869,671', 'Random House',
        'Crime, Thriller & Adventure'],
       ['83', 'Small Island', 'Levy, Andrea', '869,659', 'Headline',
        'General & Literary Fiction'],
       ['84', 'Nigella Express', 'Lawson, Nigella', '862,602',
        'Random House', 'Food & Drink: General'],
       ['85', 'Brick Lane', 'Ali, Monica', '856,540', 'Transworld',
        'General & Literary Fiction'],
       ['86', "Memory Keeper's Daughter,The", 'Edwards, Kim', '845,858',
        'Penguin', 'General & Literary Fiction'],
       ['87', 'Room on the Broom', 'Donaldson, Julia', '842,535',
        'Pan Macmillan', 'Picture Books'],
       ['88', 'About a Boy', 'Hornby, Nick', '828,215', 'Penguin',
        'General & Literary Fiction'],
       ['89', 'My Booky Wook', 'Brand, Russell', '820,563',
        'Hodder & Stoughton', 'Autobiography: The Arts'],
       ['90', 'God Delusion,The', 'Dawkins, Richard', '816,907',
        'Transworld', 'Popular Science'],
       ['91', '"Beano" Annual,The', '0', '816,585', 'D.C. Thomson',
        "Children's Annuals"],
       ['92', 'White Teeth', 'Smith, Zadie', '815,586', 'Penguin',
        'General & Literary Fiction'],
       ['93', 'House at Riverton,The', 'Morton, Kate', '814,370',
        'Pan Macmillan', 'General & Literary Fiction'],
       ['94', 'Book Thief,The', 'Zusak, Markus', '809,641', 'Transworld',
        'General & Literary Fiction'],
       ['95', 'Nights of Rain and Stars', 'Binchy, Maeve', '808,900',
        'Orion', 'General & Literary Fiction'],
       ['96', 'Ghost,The', 'Harris, Robert', '807,311', 'Random House',
        'General & Literary Fiction'],
       ['97', 'Happy Days with the Naked Chef', 'Oliver, Jamie',
        '794,201', 'Penguin', 'Food & Drink: General'],
       ['98', 'Hunger Games,The:Hunger Games Trilogy',
        'Collins, Suzanne', '792,187', 'Scholastic Ltd.',
        'Young Adult Fiction'],
       ['99',
        "Lost Boy,The:A Foster Child's Search for the Love of a Family",
        'Pelzer, Dave', '791,507', 'Orion', 'Biography: General'],
       ['100',
        "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours",
        'Oliver, Jamie', '791,095', 'Penguin', 'Food & Drink: General']],
      dtype='<U70')

In [282]:
pd.DataFrame(data=novels,columns=cols)

,Rank,Title,Author,Volume Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## Question 7:
Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/ You have
to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [321]:
driver7=webdriver.Chrome()
driver7.get('https://www.imdb.com/chart/tvmeter/?ref_=nv_tvv_mptv')

In [322]:
tv_href=[]
tv_url=driver7.find_elements(By.XPATH,'//div[@class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-b189961a-9 iALATN cli-title"]/a')

for url in tv_url:
    tv_href.append(url.get_attribute('href'))
tv_href

['https://www.imdb.com/title/tt12262202/?ref_=chttvm_t_1',
 'https://www.imdb.com/title/tt16283824/?ref_=chttvm_t_2',
 'https://www.imdb.com/title/tt8740790/?ref_=chttvm_t_3',
 'https://www.imdb.com/title/tt12637874/?ref_=chttvm_t_4',
 'https://www.imdb.com/title/tt11198330/?ref_=chttvm_t_5',
 'https://www.imdb.com/title/tt0944947/?ref_=chttvm_t_6',
 'https://www.imdb.com/title/tt19231492/?ref_=chttvm_t_7',
 'https://www.imdb.com/title/tt1190634/?ref_=chttvm_t_8',
 'https://www.imdb.com/title/tt11712058/?ref_=chttvm_t_9',
 'https://www.imdb.com/title/tt11815682/?ref_=chttvm_t_10',
 'https://www.imdb.com/title/tt7440726/?ref_=chttvm_t_11',
 'https://www.imdb.com/title/tt31433814/?ref_=chttvm_t_12',
 'https://www.imdb.com/title/tt2788316/?ref_=chttvm_t_13',
 'https://www.imdb.com/title/tt26426076/?ref_=chttvm_t_14',
 'https://www.imdb.com/title/tt0452046/?ref_=chttvm_t_15',
 'https://www.imdb.com/title/tt0413573/?ref_=chttvm_t_16',
 'https://www.imdb.com/title/tt19380952/?ref_=chttvm_t_17',
 'https://www.imdb.com/title/tt6226232/?ref_=chttvm_t_18',
 'https://www.imdb.com/title/tt1632701/?ref_=chttvm_t_19',
 'https://www.imdb.com/title/tt14452776/?ref_=chttvm_t_20',
 'https://www.imdb.com/title/tt22188654/?ref_=chttvm_t_21',
 'https://www.imdb.com/title/tt13649112/?ref_=chttvm_t_22',
 'https://www.imdb.com/title/tt7587890/?ref_=chttvm_t_23',
 'https://www.imdb.com/title/tt0903747/?ref_=chttvm_t_24',
 'https://www.imdb.com/title/tt31491435/?ref_=chttvm_t_25',
 'https://www.imdb.com/title/tt4574334/?ref_=chttvm_t_26',
 'https://www.imdb.com/title/tt9055008/?ref_=chttvm_t_27',
 'https://www.imdb.com/title/tt4236770/?ref_=chttvm_t_28',
 'https://www.imdb.com/title/tt1520211/?ref_=chttvm_t_29',
 'https://www.imdb.com/title/tt11685912/?ref_=chttvm_t_30',
 'https://www.imdb.com/title/tt0773262/?ref_=chttvm_t_31',
 'https://www.imdb.com/title/tt1640719/?ref_=chttvm_t_32',
 'https://www.imdb.com/title/tt21072112/?ref_=chttvm_t_33',
 'https://www.imdb.com/title/tt13210838/?ref_=chttvm_t_34',
 'https://www.imdb.com/title/tt0436992/?ref_=chttvm_t_35',
 'https://www.imdb.com/title/tt5171438/?ref_=chttvm_t_36',
 'https://www.imdb.com/title/tt7235466/?ref_=chttvm_t_37',
 'https://www.imdb.com/title/tt0203259/?ref_=chttvm_t_38',
 'https://www.imdb.com/title/tt13016388/?ref_=chttvm_t_39',
 'https://www.imdb.com/title/tt0460681/?ref_=chttvm_t_40',
 'https://www.imdb.com/title/tt12809988/?ref_=chttvm_t_41',
 'https://www.imdb.com/title/tt11646832/?ref_=chttvm_t_42',
 'https://www.imdb.com/title/tt0141842/?ref_=chttvm_t_43',
 'https://www.imdb.com/title/tt0386676/?ref_=chttvm_t_44',
 'https://www.imdb.com/title/tt0412142/?ref_=chttvm_t_45',
 'https://www.imdb.com/title/tt0364845/?ref_=chttvm_t_46',
 'https://www.imdb.com/title/tt2356777/?ref_=chttvm_t_47',
 'https://www.imdb.com/title/tt0491738/?ref_=chttvm_t_48',
 'https://www.imdb.com/title/tt1586680/?ref_=chttvm_t_49',
 'https://www.imdb.com/title/tt0898266/?ref_=chttvm_t_50',
 'https://www.imdb.com/title/tt27792190/?ref_=chttvm_t_51',
 'https://www.imdb.com/title/tt9813792/?ref_=chttvm_t_52',
 'https://www.imdb.com/title/tt16418808/?ref_=chttvm_t_53',
 'https://www.imdb.com/title/tt2442560/?ref_=chttvm_t_54',
 'https://www.imdb.com/title/tt9022422/?ref_=chttvm_t_55',
 'https://www.imdb.com/title/tt9335498/?ref_=chttvm_t_56',
 'https://www.imdb.com/title/tt2085059/?ref_=chttvm_t_57',
 'https://www.imdb.com/title/tt0185906/?ref_=chttvm_t_58',
 'https://www.imdb.com/title/tt2560140/?ref_=chttvm_t_59',
 'https://www.imdb.com/title/tt21433150/?ref_=chttvm_t_60',
 'https://www.imdb.com/title/tt11016042/?ref_=chttvm_t_61',
 'https://www.imdb.com/title/tt1442437/?ref_=chttvm_t_62',
 'https://www.imdb.com/title/tt3032476/?ref_=chttvm_t_63',
 'https://www.imdb.com/title/tt0411008/?ref_=chttvm_t_64',
 'https://www.imdb.com/title/tt0108778/?ref_=chttvm_t_65',
 'https://www.imdb.com/title/tt0312172/?ref_=chttvm_t_66',
 'https://www.imdb.com/title/tt13875494/?ref_=chttvm_t_67',
 'https://www.imdb.com/title/tt12004706/?ref_=chttvm_t_68',
 'https://www.imdb.com/title/tt3006802/?ref_=chttvm_t_69',
 'https://www.imdb.com/title/tt2802850/?ref_=chttvm_t_70',
 'https://www.imdb.com/title/tt3581920/?ref_=chttvm_t_71',
 'https://www.imdb.com/title/tt2861424/?ref_=chttvm_t_72',
 'https://www.imdb.com/title/tt1844624/?ref_=chttvm_t_73',
 'https://www.imdb.com/title/tt6470478/?ref_=chttvm_t_74',
 'https://www.imdb.com/title/tt10986410/?ref_=chttvm_t_75',
 'https://www.imdb.com/title/tt2306299/?ref_=chttvm_t_76',
 'https://www.imdb.com/title/tt7631058/?ref_=chttvm_t_77',
 'https://www.imdb.com/title/tt12074628/?ref_=chttvm_t_78',
 'https://www.imdb.com/title/tt14404618/?ref_=chttvm_t_79',
 'https://www.imdb.com/title/tt0472954/?ref_=chttvm_t_80',
 'https://www.imdb.com/title/tt15845610/?ref_=chttvm_t_81',
 'https://www.imdb.com/title/tt3960394/?ref_=chttvm_t_82',
 'https://www.imdb.com/title/tt4786824/?ref_=chttvm_t_83',
 'https://www.imdb.com/title/tt7660850/?ref_=chttvm_t_84',
 'https://www.imdb.com/title/tt1312171/?ref_=chttvm_t_85',
 'https://www.imdb.com/title/tt1358522/?ref_=chttvm_t_86',
 'https://www.imdb.com/title/tt11280740/?ref_=chttvm_t_87',
 'https://www.imdb.com/title/tt2467372/?ref_=chttvm_t_88',
 'https://www.imdb.com/title/tt0388629/?ref_=chttvm_t_89',
 'https://www.imdb.com/title/tt0460627/?ref_=chttvm_t_90',
 'https://www.imdb.com/title/tt14661396/?ref_=chttvm_t_91',
 'https://www.imdb.com/title/tt9471404/?ref_=chttvm_t_92',
 'https://www.imdb.com/title/tt0306414/?ref_=chttvm_t_93',
 'https://www.imdb.com/title/tt6111130/?ref_=chttvm_t_94',
 'https://www.imdb.com/title/tt9859436/?ref_=chttvm_t_95',
 'https://www.imdb.com/title/tt8772296/?ref_=chttvm_t_96',
 'https://www.imdb.com/title/tt32307218/?ref_=chttvm_t_97',
 'https://www.imdb.com/title/tt17677860/?ref_=chttvm_t_98',
 'https://www.imdb.com/title/tt9288030/?ref_=chttvm_t_99',
 'https://www.imdb.com/title/tt2261391/?ref_=chttvm_t_100']

In [323]:
tv_titles=[]
tv_year=[]
tv_genres=[]
tv_runtime=[]
tv_ratings=[]
tv_votes=[]

for url in tv_href:
    driver7.get(url)
    try:
        #Extracting titles
        title=driver7.find_element(By.XPATH,'//span[contains(@class,"hero__primary-text")]')
        tv_titles.append(title.text)
    except:
        tv_titles.append('-')
        
        
    try:
        #Extracting year
        year=driver7.find_element(By.XPATH,'//ul[@class="ipc-inline-list ipc-inline-list--show-dividers sc-d8941411-2 cdJsTz baseAlt"]/li[2]/a')
        tv_year.append(year.text)
    except:
        tv_year.append('-')
    
    try:
        #Extracting genre
        genre=driver7.find_element(By.XPATH,'//div[@class="ipc-chip-list__scroller"]')
        tv_genres.append(genre.text)
    except:
        tv_genres.append('-')
    
    try:
        #Extracting Run Time
        time=driver7.find_element(By.XPATH,'//ul[@class="ipc-inline-list ipc-inline-list--show-dividers sc-d8941411-2 cdJsTz baseAlt"]/li[4]')
        tv_runtime.append(time.text)
    except:
        tv_runtime.append('-')
    
    try:
        #Extracting ratings
        rating=driver7.find_element(By.XPATH,'//div[@class="sc-3a4309f8-0 bjXIAP sc-b7c53eda-1 iIQkEw"]/div/div/a/span/div/div[2]/div/span')
        tv_ratings.append(rating.text)
    except:
        tv_ratings.append('-')
    
    try:
        #extracting votes
        votes=driver7.find_element(By.XPATH,'/html/body/div[2]/main/div/section[1]/section/div[3]/section/section/div[3]/div[2]/div[2]/div[1]/div/div[1]/a/span/div/div[2]/div[3]')
        tv_votes.append(votes.text)
    except:
        tv_votes.append('-')

In [314]:
tv_titles.clear()
tv_year.clear()
tv_genres.clear()
tv_runtime.clear()
tv_ratings.clear()
tv_votes.clear()

In [324]:
len(tv_titles)

100

In [325]:
len(tv_genres)

100

In [326]:
len(tv_runtime)

100

In [327]:
len(tv_ratings)

100

In [328]:
len(tv_votes)

100

In [336]:
topshows=pd.DataFrame({"Title":tv_titles,"Year":tv_year,"Genre":tv_genres,"Runtime":tv_runtime,"Ratings":tv_ratings})

In [337]:
topshows

,Title,Year,Genre,Runtime,Ratings
0,The Acolyte,2024–,Action\nAdventure\nDrama,35m,4.3
1,Eric,2024,Crime\nDrama\nThriller,53m,7.0
2,Bridgerton,2020–,Drama\nRomance,1h,7.4
3,Fallout,2024–,Action\nAdventure\nDrama,1h,8.4
4,House of the Dragon,2022–,Action\nAdventure\nDrama,50m,8.4
...,...,...,...,...,...
95,Euphoria,2019–,Drama,55m,8.3
96,Dancing for the Devil: The 7M TikTok Cult,2024,Documentary\nCrime,1h,6.1
97,Presumed Innocent,2024–,Crime\nDrama\nMystery,-,7.2
98,Reacher,2022–,Action\nCrime\nDrama,50m,8.1
99,Chicago Fire,2012–,Action\nDrama,43m,8.0

In [339]:
max(topshows['Ratings'])

'9.5'

## Question 8:
Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/ You
have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute G) Year
 Note: - from the home page you have to go to the Show All Dataset page through code.

In [394]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time

In [434]:
driver8=webdriver.Chrome()
driver8.get('https://archive.ics.uci.edu/')

In [435]:
repo_href=driver8.find_element(By.XPATH,'//a[@class="btn-primary btn"]')
href=repo_href.get_attribute('href')
driver8.get(href)

In [389]:
dataset_urls=[]
for i in range(66):
    set_href=WebDriverWait(driver8,10).until(EC.presence_of_all_elements_located((By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')))

    for url in set_href:
        get_url=url.get_attribute('href')
        dataset_urls.append(get_url)
    try:
        next_button = driver8.find_element(By.XPATH,'//button[contains(@aria-label,"Next Page")]')
        next_button.click()
    except ElementClickInterceptedException:
        # If the button is not clickable due to an overlay, wait for the overlay to disappear
        WebDriverWait(driver8, 10).until(
            EC.invisibility_of_element_located((By.XPATH, '//div[@class="btn-group"]/button[2]'))
        )
        next_button = WebDriverWait(driver8, 10).until(
            EC.element_to_be_clickable((By.XPATH, '//button[contains(@aria-label,"Next Page")]'))
        )
        next_button.click()
    
    # Wait a bit before the next iteration to ensure the new page is loaded
    time.sleep(10)

In [397]:
len(dataset_urls)

660

In [392]:
dataset_name=[]
dataset_type=[]
dataset_task=[]
dataset_attribute=[]
no_of_attribute=[]
no_of_instances=[]
dataset_year=[]

In [409]:
row=[]
for u in dataset_urls:
    driver8.get(u)
    try:
        d_name=driver8.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        dataset_name.append(d_name.text)
    except:
        d_name=driver8.find_element(By.XPATH,'//h1[@class="text-3xl font-semibold text-primary-content"]')
        dataset_name.append('-')
    
    for i in range(1,7):
        try:
            d_row=driver8.find_element(By.XPATH,'//div[@class="relative flex flex-col gap-4 bg-base-100 p-4 shadow"]/div[2]/div['+str(i)+']/p')
            row.append(d_row.text)
        except:
            d_row=driver8.find_element(By.XPATH,'//div[@class="relative flex flex-col gap-4 bg-base-100 p-4 shadow"]/div[2]/div['+str(i)+']/p')
            row.append('-')

In [436]:
for u in dataset_urls:
    driver8.get(u)
    try:
        d_name=driver8.find_element(By.XPATH,'//div[@class="relative flex flex w-full items-center gap-4 bg-primary p-2"]/div[2]/div/h1')
        dataset_name.append(d_name.text)
    except:
        d_name=driver8.find_element(By.XPATH,'//h1[contains(@class,"text-3xl font-semibold text-primary-content")]')
        dataset_name.append(d_name.text)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//h1[contains(@class,"text-3xl font-semibold text-primary-content")]"}
  (Session info: chrome=125.0.6422.142); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001092436b8 chromedriver + 6149816
1   chromedriver                        0x000000010923acda chromedriver + 6114522
2   chromedriver                        0x0000000108cc7d5c chromedriver + 400732
3   chromedriver                        0x0000000108d14aa5 chromedriver + 715429
4   chromedriver                        0x0000000108d14bf1 chromedriver + 715761
5   chromedriver                        0x0000000108d59dd4 chromedriver + 998868
6   chromedriver                        0x0000000108d37cdd chromedriver + 859357
7   chromedriver                        0x0000000108d570db chromedriver + 987355
8   chromedriver                        0x0000000108d37a53 chromedriver + 858707
9   chromedriver                        0x0000000108d076d5 chromedriver + 661205
10  chromedriver                        0x0000000108d07f6e chromedriver + 663406
11  chromedriver                        0x0000000109204cf0 chromedriver + 5893360
12  chromedriver                        0x000000010920a4bc chromedriver + 5915836
13  chromedriver                        0x00000001091e68b4 chromedriver + 5769396
14  chromedriver                        0x000000010920af89 chromedriver + 5918601
15  chromedriver                        0x00000001091d7ec4 chromedriver + 5709508
16  chromedriver                        0x000000010922b008 chromedriver + 6049800
17  chromedriver                        0x000000010922b1c7 chromedriver + 6050247
18  chromedriver                        0x000000010923a88e chromedriver + 6113422
19  libsystem_pthread.dylib             0x00007ff80a25c1d3 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff80a257bd3 thread_start + 15

In [504]:
len(row)

3960

In [505]:
len(dataset_name)

660

In [506]:
row

['Tabular',
 'Biology',
 'Classification',
 'Real',
 '150',
 '4',
 'Multivariate',
 'Biology',
 'Classification',
 'Integer, Real',
 '13611',
 '16',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer, Real',
 '303',
 '13',
 'Multivariate',
 'Biology',
 'Classification',
 'Real',
 '3810',
 '7',
 'Multivariate',
 'Biology',
 'Classification',
 'Real, Integer',
 '900',
 '7',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical, Integer',
 '48842',
 '14',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Real',
 '569',
 '30',
 'Tabular',
 'Physics and Chemistry',
 'Classification',
 'Integer, Real',
 '178',
 '13',
 'Multivariate',
 'Business',
 'Classification, Regression',
 'Real',
 '4898',
 '11',
 'Multivariate',
 'Business',
 'Classification',
 'Categorical, Integer',
 '45211',
 '16',
 'Multivariate, Time-Series',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer',
 '1',
 '20',
 'Multivariate',
 'Other',
 'Classification',
 'Categorical',
 '1728',
 '6',
 'Multivariate',
 'Social Science',
 'Classification, Regression',
 'Integer',
 '649',
 '30',
 'Tabular',
 'Biology',
 'Classification, Regression',
 'Categorical, Integer, Real',
 '4177',
 '8',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical',
 '8124',
 '22',
 'Multivariate, Sequential, Time-Series',
 'Business',
 'Classification, Clustering',
 'Integer, Real',
 '541909',
 '6',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical, Integer',
 '1000',
 '20',
 'Multivariate',
 'Other',
 'Regression',
 'Categorical, Integer, Real',
 '205',
 '25',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical, Integer',
 '48842',
 '14',
 'Tabular',
 'Social Science',
 'Classification',
 'Real, Categorical, Integer',
 '4424',
 '36',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical',
 '286',
 '9',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Integer, Real',
 '4601',
 '57',
 'Multivariate',
 'Other',
 'Regression',
 'Real, Categorical, Integer',
 '398',
 '7',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Integer',
 '699',
 '9',
 'Multivariate, Time-Series',
 'Computer Science',
 'Regression',
 'Real',
 '9358',
 '15',
 'Multivariate',
 'Business',
 'Classification',
 'Integer, Real',
 '30000',
 '23',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Real',
 '214',
 '9',
 'Multivariate, Time-Series',
 'Computer Science',
 'Classification, Clustering',
 '-',
 '10299',
 '-',
 'Multivariate',
 'Social Science',
 'Regression',
 'Integer, Real',
 '17389',
 '13',
 'Multivariate',
 'Business',
 'Classification',
 'Categorical, Integer, Real',
 '690',
 '15',
 'Multivariate, Sequential, Time-Series, Text',
 'Business',
 'Classification, Regression, Clustering',
 'Integer, Real',
 '1067371',
 '-',
 'Multivariate, Domain-Theory',
 'Health and Medicine',
 'Classification',
 'Categorical, Real',
 '7200',
 '5',
 'Multivariate, Text, Domain-Theory',
 'Computer Science',
 'Classification, Clustering',
 'Real',
 '5574',
 '-',
 'Multivariate',
 'Health and Medicine',
 'Classification, Regression, Clustering',
 'Integer',
 '2111',
 '16',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Integer',
 '5620',
 '64',
 'Multivariate, Time-Series',
 'Physics and Chemistry',
 'Regression, Clustering',
 'Real',
 '2075259',
 '9',
 'Multivariate',
 'Business',
 'Classification, Clustering',
 'Integer, Real',
 '12330',
 '17',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Real',
 '19020',
 '10',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical, Integer',
 '101',
 '16',
 'Multivariate',
 'Climate and Environment',
 'Regression',
 'Real',
 '517',
 '12',
 'Multivariate',
 'Health and Medicine',
 'Classification, Regression, Clustering',
 'Integer, Real',
 '299',
 '12',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical, Integer',
 '581012',
 '54',
 'Multivariate',
 'Health and Medicine',
 'Classification, Clustering',
 'Categorical, Integer',
 '101766',
 '47',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Integer',
 '32',
 '56',
 'Tabular, Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer',
 '253680',
 '21',
 'Multivariate',
 'Health and Medicine',
 'Regression',
 'Categorical, Integer, Real',
 '345',
 '5',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Integer',
 '20000',
 '16',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Integer, Real',
 '351',
 '34',
 'Multivariate',
 'Computer Science',
 'Regression',
 'Integer',
 '209',
 '10',
 'Multivariate',
 'Business',
 'Regression',
 'Integer, Real',
 '414',
 '6',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer, Real',
 '155',
 '19',
 'Multivariate',
 'Biology',
 'Classification, Clustering',
 'Real',
 '210',
 '-',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Categorical, Integer, Real',
 '3279',
 '1558',
 'Multivariate',
 'Computer Science',
 'Classification, Regression',
 'Integer, Real',
 '768',
 '8',
 'Multivariate',
 'Business',
 'Classification, Clustering',
 'Integer',
 '440',
 '7',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Real',
 '208',
 '60',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical',
 '435',
 '16',
 'Multivariate',
 'Business',
 'Regression',
 'Integer, Real',
 '8760',
 '13',
 'Multivariate',
 'Other',
 'Classification',
 'Real',
 '400',
 '24',
 'Multivariate',
 'Physics and Chemistry',
 'Regression',
 'Real',
 '1030',
 '8',
 'Multivariate',
 'Biology',
 'Classification',
 'Real',
 '1484',
 '8',
 'Multivariate',
 'Games',
 'Classification',
 'Categorical',
 '958',
 '9',
 'Multivariate, Time-Series',
 'Computer Science',
 'Classification, Regression, Causal-Discovery',
 'Real',
 '10000',
 '6',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Real',
 '197',
 '22',
 'Multivariate',
 'Other',
 'Classification',
 'Real',
 '2310',
 '19',
 'Multivariate',
 'Business',
 'Classification, Regression, Clustering',
 'Categorical, Integer',
 '10000',
 '21',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer, Real',
 '452',
 '279',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical',
 '12960',
 '8',
 'Time-Series',
 'Computer Science',
 'Regression, Clustering',
 'Real',
 '370',
 '140256',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Integer',
 '10992',
 '16',
 'Tabular',
 'Computer Science',
 'Classification',
 'Integer',
 '11055',
 '30',
 'Multivariate',
 'Business',
 'Classification',
 'Categorical, Integer, Real',
 '690',
 '14',
 'Text',
 'Other',
 '-',
 '-',
 '20000',
 '-',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Real',
 '270',
 '13',
 'Multivariate, Time-Series',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer, Real',
 '122',
 '-',
 'Multivariate',
 'Business',
 'Classification, Regression',
 'Integer, Real',
 '39797',
 '58',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Real',
 '1372',
 '4',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical',
 '625',
 '4',
 'Multivariate',
 'Health and Medicine',
 'Classification, Regression',
 'Real',
 '198',
 '33',
 'Multivariate, Time-Series',
 'Computer Science',
 'Regression',
 'Real',
 '19735',
 '28',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer',
 '366',
 '34',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical',
 '307',
 '35',
 'Multivariate',
 'Social Science',
 'Classification',
 'Integer',
 '145',
 '31',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Categorical, Integer',
 '520',
 '16',
 'Multivariate',
 'Social Science',
 'Regression',
 'Real',
 '1994',
 '127',
 'Multivariate',
 'Computer Science',
 'Regression',
 'Real',
 '9568',
 '4',
 'Multivariate, Time-Series',
 'Business',
 'Classification, Regression',
 'Integer, Real',
 '1197',
 '14',
 'Multivariate',
 'Physics and Chemistry',
 'Regression',
 'Categorical',
 '1389',
 '10',
 'Multivariate',
 'Biology',
 'Classification',
 'Real',
 '336',
 '7',
 'Multivariate, Text',
 'Health and Medicine',
 'Classification, Regression, Clustering',
 'Integer',
 '215063',
 '6',
 'Multivariate, Relational',
 'Other',
 '-',
 '-',
 '10000',
 '-',
 'Text',
 'Business',
 'Classification',
 'Categorical',
 '21578',
 '5',
 'Text',
 'Other',
 'Classification',
 '-',
 '3000',
 '-',
 '-',
 'Physics and Chemistry',
 'Classification',
 'Real',
 '11000000',
 '-',
 'Multivariate',
 'Other',
 'Classification',
 'Integer',
 '946',
 '18',
 'Multivariate',
 'Climate and Environment',
 'Classification',
 'Integer',
 '6435',
 '36',
 'Tabular',
 'Health and Medicine',
 'Classification',
 'Categorical',
 '714',
 '14',
 'Multivariate',
 'Social Science',
 'Regression, Description',
 'Categorical, Integer',
 '9000',
 '-',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Integer',
 '58000',
 '7',
 'Multivariate',
 'Social Science',
 'Classification',
 'Real',
 '1885',
 '12',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer',
 '1473',
 '9',
 'Multivariate',
 'Other',
 'Classification',
 'Categorical',
 '24',
 '3',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Real',
 '7797',
 '617',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical, Integer, Real',
 '368',
 '27',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Categorical, Integer',
 '4000000',
 '-',
 'Multivariate, Time-Series',
 'Computer Science',
 'Classification, Regression',
 'Real',
 '63000000',
 '-',
 'Tabular, Multivariate, Time-Series',
 'Computer Science',
 'Classification',
 'Real',
 '1516948',
 '15',
 'Multivariate',
 'Other',
 'Classification',
 'Categorical, Integer',
 '194',
 '30',
 'Other',
 'Computer Science',
 'Regression',
 '-',
 '705',
 '-',
 'Tabular',
 'Health and Medicine',
 'Regression',
 'Integer, Real',
 '5875',
 '19',
 'Image',
 'Other',
 'Classification',
 'Integer',
 '640',
 '-',
 'Multivariate',
 'Games',
 'Classification',
 'Categorical, Integer',
 '1025010',
 '10',
 'Tabular, Multivariate, Other',
 'Engineering',
 'Classification, Clustering',
 'Real, Integer',
 '338',
 '3',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Real',
 '1700',
 '111',
 'Multivariate, Time-Series',
 'Business',
 'Classification, Clustering',
 'Integer, Real',
 '740',
 '19',
 'Multivariate',
 'Engineering',
 'Regression',
 '-',
 '2101',
 '-',
 'Multivariate, Data-Generator',
 'Physics and Chemistry',
 'Classification',
 'Real',
 '5000',
 '21',
 'Tabular, Multivariate',
 'Health and Medicine',
 'Classification, Other',
 'Real, Categorical, Integer',
 '839',
 '23',
 'Sequential, Domain-Theory',
 'Biology',
 'Classification',
 'Categorical',
 '106',
 '-',
 'Multivariate',
 'Biology',
 'Classification',
 'Categorical',
 '47',
 '35',
 'Multivariate',
 'Business',
 'Classification, Regression',
 'Integer',
 '3150',
 '13',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Integer, Real',
 '583',
 '10',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Integer',
 '306',
 '3',
 'Tabular',
 'Health and Medicine',
 'Classification',
 'Real, Categorical, Integer',
 '6287',
 '7',
 '-',
 'Biology',
 '-',
 '-',
 '-',
 '-',
 'Multivariate',
 'Other',
 'Classification',
 'Categorical',
 '432',
 '6',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical',
 '16',
 '4',
 'Other',
 'Other',
 'Other',
 '-',
 '1',
 '-',
 '-',
 'Computer Science',
 'Recommender-Systems',
 'Categorical',
 '37711',
 '294',
 'Tabular, Sequential, Multivariate',
 'Engineering',
 'Classification, Regression, Clustering',
 'Real, Categorical',
 '123117',
 '83',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical, Integer, Real',
 '132',
 '9',
 'Multivariate',
 'Social Science',
 'Classification',
 'Categorical, Integer',
 '299285',
 '41',
 'Multivariate, Sequential',
 'Business',
 'Classification, Regression, Clustering',
 'Integer, Real',
 '165474',
 '14',
 'Multivariate',
 'Health and Medicine',
 'Classification, Clustering',
 'Integer, Real',
 '615',
 '12',
 'Multivariate',
 'Computer Science',
 'Classification',
 'Integer, Real',
 '2000',
 '-',
 'Multivariate, Time-Series',
 'Climate and Environment',
 'Regression',
 'Integer, Real',
 '420768',
 '-',
 'Multivariate',
 'Social Science',
 'Clustering',
 'Categorical',
 '2458285',
 '68',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Integer, Real',
 '858',
 '36',
 'Multivariate',
 'Business',
 'Classification',
 'Integer',
 '6819',
 '95',
 'Tabular',
 'Health and Medicine',
 'Classification',
 '-',
 '174',
 '451',
 'Multivariate, Image',
 'Climate and Environment',
 'Other',
 'Real',
 '1024',
 '10',
 'Multivariate, Text',
 'Other',
 'Classification, Clustering',
 'Real',
 '980',
 '10',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Integer',
 '476',
 '168',
 'Sequential, Domain-Theory',
 'Biology',
 'Classification',
 'Categorical',
 '3190',
 '60',
 'Multivariate',
 'Health and Medicine',
 'Classification, Regression',
 'Real',
 '100',
 '9',
 'Multivariate, Spatial',
 'Games',
 'Classification',
 'Categorical',
 '67557',
 '42',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical',
 '339',
 '17',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Categorical',
 '267',
 '22',
 'Tabular, Multivariate',
 'Health and Medicine',
 'Classification, Regression',
 'Categorical, Integer',
 '2139',
 '23',
 'Tabular',
 'Health and Medicine',
 'Regression',
 'Real, Categorical',
 '1020',
 '33',
 'Multivariate',
 'Business',
 'Classification',
 'Real',
 '10503',
 '65',
 'Multivariate',
 'Games',
 'Classification',
 'Categorical',
 '3196',
 '35',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Real, Integer',
 '1013',
 '6',
 'Image',
 'Physical Science',
 'Classification',
 'Real',
 '50000',
 '-',
 'Multivariate, Sequential, Time-Series',
 'Other',
 'Regression',
 'Integer, Real',
 '48204',
 '8',
 'Multivariate',
 'Computer Science',
 'Regression',
 'Categorical, Integer',
 '167',
 '4',
 'Tabular',
 'Health and Medicine',
 'Classification',
 'Real, Categorical',
 '418',
 '17',
 'Tabular, Image',
 'Health and Medicine',
 'Classification',
 'Real, Categorical, Integer',
 '782',
 '53',
 'Text',
 'Other',
 'Clustering',
 'Integer',
 '8000000',
 '100000',
 'Tabular',
 'Biology',
 'Classification',
 'Real',
 '61068',
 '20',
 'Tabular',
 'Health and Medicine',
 'Classification',
 'Real, Categorical, Integer',
 '383',
 '16',
 'Time-Series',
 'Business',
 'Classification, Clustering',
 'Integer, Real',
 '750',
 '15',
 'Multivariate, Time-Series',
 'Business',
 'Clustering',
 'Integer, Real',
 '811',
 '106',
 'Multivariate, Time-Series',
 'Health and Medicine',
 'Classification, Regression',
 'Real',
 '14057567',
 '15',
 'Multivariate',
 'Health and Medicine',
 'Classification',
 'Real',
 '2126',
 '21',
 'Multivariate',
 'Physics and Chemistry',
 'Regression',
 'Integer',
 '23',
 '4',
 'Multivariate',
 'Physics and Chemistry',
 'Classification',
 'Categorical, Integer, Real',
 ...]

In [507]:
dataset_name

['Iris',
 'Dry Bean',
 'Heart Disease',
 'Rice (Cammeo and Osmancik)',
 'Raisin',
 'Adult',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Wine',
 'Wine Quality',
 'Bank Marketing',
 'Diabetes',
 'Car Evaluation',
 'Student Performance',
 'Abalone',
 'Mushroom',
 'Online Retail',
 'Statlog (German Credit Data)',
 'Automobile',
 'Census Income',
 "Predict Students' Dropout and Academic Success",
 'Breast Cancer',
 'Spambase',
 'Auto MPG',
 'Breast Cancer Wisconsin (Original)',
 'Air Quality',
 'Default of Credit Card Clients',
 'Glass Identification',
 'Human Activity Recognition Using Smartphones',
 'Bike Sharing',
 'Credit Approval',
 'Online Retail II',
 'Thyroid Disease',
 'SMS Spam Collection',
 'Estimation of Obesity Levels Based On Eating Habits and Physical Condition',
 'Optical Recognition of Handwritten Digits',
 'Individual Household Electric Power Consumption',
 'Online Shoppers Purchasing Intention Dataset',
 'MAGIC Gamma Telescope',
 'Zoo',
 'Forest Fires',
 'Heart Failure Clinical Records',
 'Covertype',
 'Diabetes 130-US Hospitals for Years 1999-2008',
 'Lung Cancer',
 'CDC Diabetes Health Indicators',
 'Liver Disorders',
 'Letter Recognition',
 'Ionosphere',
 'Computer Hardware',
 'Real Estate Valuation',
 'Hepatitis',
 'Seeds',
 'Internet Advertisements',
 'Energy Efficiency',
 'Wholesale customers',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Congressional Voting Records',
 'Seoul Bike Sharing Demand',
 'Chronic Kidney Disease',
 'Concrete Compressive Strength',
 'Yeast',
 'Tic-Tac-Toe Endgame',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Parkinsons',
 'Image Segmentation',
 'Apartment for Rent Classified',
 'Arrhythmia',
 'Nursery',
 'ElectricityLoadDiagrams20112014',
 'Pen-Based Recognition of Handwritten Digits',
 'Phishing Websites',
 'Statlog (Australian Credit Approval)',
 'Twenty Newsgroups',
 'Statlog (Heart)',
 'EEG Database',
 'Online News Popularity',
 'Banknote Authentication',
 'Balance Scale',
 'Breast Cancer Wisconsin (Prognostic)',
 'Appliances Energy Prediction',
 'Dermatology',
 'Soybean (Large)',
 'Higher Education Students Performance Evaluation',
 'Early Stage Diabetes Risk Prediction',
 'Communities and Crime',
 'Combined Cycle Power Plant',
 'Productivity Prediction of Garment Employees',
 'Solar Flare',
 'Ecoli',
 'Drug Reviews (Drugs.com)',
 'Movie',
 'Reuters-21578 Text Categorization Collection',
 'Sentiment Labelled Sentences',
 'HIGGS',
 'Statlog (Vehicle Silhouettes)',
 'Statlog (Landsat Satellite)',
 'National Poll on Healthy Aging (NPHA)',
 'Insurance Company Benchmark (COIL 2000)',
 'Statlog (Shuttle)',
 'Drug Consumption (Quantified)',
 'Contraceptive Method Choice',
 'Lenses',
 'ISOLET',
 'Horse Colic',
 'KDD Cup 1999 Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'MetroPT-3 Dataset',
 'Flags',
 'Water Quality Prediction',
 'Parkinsons Telemonitoring',
 'CMU Face Images',
 'Poker Hand',
 'Land Mines',
 'Myocardial infarction complications',
 'Absenteeism at work',
 'Traffic Flow Forecasting',
 'Waveform Database Generator (Version 1)',
 'Glioma Grading Clinical and Mutation Features',
 'Molecular Biology (Promoter Gene Sequences)',
 'Soybean (Small)',
 'Iranian Churn',
 'ILPD (Indian Liver Patient Dataset)',
 "Haberman's Survival",
 'National Health and Nutrition Health Survey 2013-2014 (NHANES) Age Prediction Subset',
 'Protein Data',
 "MONK's Problems",
 'Balloons',
 'Statlog Project',
 'Anonymous Microsoft Web Data',
 'RT-IoT2022',
 'Echocardiogram',
 'Census-Income (KDD)',
 'Clickstream Data for Online Shopping',
 'HCV data',
 'Multiple Features',
 'Beijing Multi-Site Air Quality',
 'US Census Data (1990)',
 'Cervical Cancer (Risk Factors)',
 'Taiwanese Bankruptcy Prediction',
 'DARWIN',
 'Cloud',
 'Travel Reviews',
 'Musk (Version 1)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Fertility',
 'Connect-4',
 'Primary Tumor',
 'SPECT Heart',
 'AIDS Clinical Trials Group Study 175',
 'Infrared Thermography Temperature',
 'Polish Companies Bankruptcy',
 'Chess (King-Rook vs. King-Pawn)',
 'Maternal Health Risk',
 'NASA Flood Extent Detection',
 'Metro Interstate Traffic Volume',
 'Servo',
 'Cirrhosis Patient Survival Prediction',
 'Regensburg Pediatric Appendicitis',
 'Bag of Words',
 'Secondary Mushroom',
 'Differentiated Thyroid Cancer Recurrence',
 'Dow Jones Index',
 'Sales Transactions Weekly',
 'Bar Crawl: Detecting Heavy Drinking',
 'Cardiotocography',
 'Challenger USA Space Shuttle O-Ring',
 'Annealing',
 'Lymphography',
 'Blood Transfusion Service Center',
 'Breast Cancer Coimbra',
 'Japanese Credit Screening',
 'Bach Chorales',
 'Algerian Forest Fires',
 'Risk Factor Prediction of Chronic Kidney Disease',
 'Room Occupancy Estimation',
 'MHEALTH',
 'PAMAP2 Physical Activity Monitoring',
 'Daily and Sports Activities',
 'TCGA Kidney Cancers',
 'Facebook Metrics',
 'DeFungi',
 'Website Phishing',
 'Beijing PM2.5',
 'South German Credit',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'In-Vehicle Coupon Recommendation',
 'Chess (King-Rook vs. King)',
 'Page Blocks Classification',
 'HAR70+',
 'Cylinder Bands',
 'Daily Demand Forecasting Orders',
 'Gender by Name',
 'EEG Eye State',
 'Hayes-Roth',
 'PhiUSIIL Phishing URL (Website)',
 'Multivariate Gait Data',
 'SUPPORT2',
 'Year Prediction MSD',
 'El Nino',
 'SECOM',
 'Smartphone Dataset for Anomaly Detection in Crowds',
 'Mammographic Mass',
 'Labor Relations',
 'HARTH',
 'Musk (Version 2)',
 'Autism Screening Adult',
 'Audiology (Original)',
 'Vertebral Column',
 'Ozone Level Detection',
 'MNIST Database of Handwritten Digits',
 'Waveform Database Generator (Version 2)',
 'Australian Sign Language Signs',
 'Facebook Live Sellers in Thailand',
 'Entree Chicago Recommendation Data',
 'Superconductivty Data',
 'Kitsune Network Attack',
 'Steel Plates Faults',
 'Audiology (Standardized)',
 'LED Display Domain',
 "Parkinson's Disease Classification",
 'Stock Portfolio Performance',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'Traffic Flow Forecasting',
 'Large-scale Wave Energy Farm',
 'gene expression cancer RNA-Seq',
 'Hierarchical Sales Data',
 'Jute Pest',
 'Electrical Grid Stability Simulated Data',
 'Product Classification and Clustering',
 'Corel Image Features',
 'SPECTF Heart',
 'ISTANBUL STOCK EXCHANGE',
 'Post-Operative Patient',
 'Heterogeneity Activity Recognition',
 'Chess (King-Rook vs. King-Knight)',
 'Plants',
 'News Popularity in Multiple Social Media Platforms',
 'Condition monitoring of hydraulic systems',
 'Molecular Biology (Protein Secondary Structure)',
 'Student Academics Performance',
 'Bosch CNC Machining Dataset',
 'Rice Leaf Diseases',
 'Basketball dataset',
 'South German Credit',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'Pedestrians in Traffic',
 'KDD Cup 1998',
 'Mice Protein Expression',
 'Gas Turbine CO and NOx Emission Data Set',
 'Drug Reviews (Druglib.com)',
 'Airfoil Self-Noise',
 'Statlog (Image Segmentation)',
 'Trains',
 'Power Consumption of Tetouan City',
 'Pittsburgh Bridges',
 'ImageNet',
 'Paper Reviews',
 'Skin Segmentation',
 'EMG Data for Gestures',
 'Tennis Major Tournament Match Statistics',
 'E. Coli Genes',
 'Shuttle Landing Control',
 'Dota2 Games Results',
 'Australian Sign Language Signs (High Quality)',
 'Single Elder Home Monitoring: Gas and Position',
 'HTRU2',
 'OPPORTUNITY Activity Recognition',
 'Occupancy Detection',
 'FMA: A Dataset For Music Analysis',
 'YouTube Spam Collection',
 'Gas Sensor Array Drift at Different Concentrations',
 'Travel Review Ratings',
 'User Knowledge Modeling',
 'Steel Industry Energy Consumption',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Cervical Cancer Behavior Risk',
 'Diabetic Retinopathy Debrecen',
 "Parkinson's Speech with Multiple Types of Sound Recordings",
 'Physical Therapy Exercises',
 'Communities and Crime Unnormalized',
 'Bone marrow transplant: children',
 'CIFAR-10',
 'Alcohol QCM Sensor',
 'Palmer Penguins',
 'Amazon Commerce Reviews',
 'NATICUSdroid (Android Permissions)',
 'Economic Sanctions',
 'Syskill and Webert Web Page Ratings',
 'Audit Data',
 'Residential Building',
 'PPG-DaLiA',
 'Amazon Access Samples',
 'Cuff-Less Blood Pressure Estimation',
 'Concrete Slump Test',
 'Detect Malware Types',
 'Mobile Robots',
 'Sepsis Survival Minimal Clinical Records',
 'Student Performance on an Entrance Examination',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Toxicity',
 'Leaf',
 'Air quality',
 'Incident management process enriched event log',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'Auction Verification',
 'Facebook Comment Volume',
 'COVID-19 Surveillance',
 'Bitcoin Heist Ransomware Address',
 'Acute Inflammations',
 'Water Treatment Plant',
 'Perfume Data',
 'Hungarian Chickenpox Cases',
 'MOVER: Medical Informatics Operating Room Vitals and Events Repository',
 'Turkish User Reviews',
 'Thoracic Surgery Data',
 'IPUMS Census Database',
 'Gas sensor array under dynamic gas mixtures',
 'Parking Birmingham',
 'UNIX User Data',
 'UJIIndoorLoc',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Open University Learning Analytics dataset',
 'Forty Soybean Cultivars from Subsequent Harvests',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Internet Firewall Data',
 'Accelerometer Gyro Mobile Phone',
 'Semeion Handwritten Digit',
 'Yacht Hydrodynamics',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Gas Sensor Array Drift Dataset',
 'Teaching Assistant Evaluation',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'Recipe Reviews and User Feedback',
 'Las Vegas Strip',
 'Chess (Domain Theories)',
 'Robot Execution Failures',
 'GPS Trajectories',
 'Gas sensor array temperature modulation',
 'Synchronous Machine',
 'Japanese Vowels',
 'News Aggregator',
 'Legal Case Reports',
 'Turkiye Student Evaluation',
 'Caesarian Section Classification Dataset',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'YouTube Multiview Video Games Dataset',
 'RealWaste',
 'Planning Relax',
 'Daphnet Freezing of Gait',
 'Cisco Secure Workload Networks of Computing Hosts',
 'Cargo 2000 Freight Tracking and Tracing',
 'QSAR fish toxicity',
 'SoDA',
 'Greenhouse Gas Observing Network',
 'Dresses_Attribute_Sales',
 'Madelon',
 'Tamilnadu Electricity Board Hourly Readings',
 'Sports articles for objectivity analysis',
 'Wall-Following Robot Navigation Data',
 'Wireless Indoor Localization',
 'Health News in Twitter',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Geographical Origin of Music',
 'APS Failure at Scania Trucks',
 'Divorce Predictors data set',
 'OpinRank Review Dataset',
 'Codon usage',
 'Exasens',
 'BlogFeedback',
 'Gas sensors for home activity monitoring',
 'Breast Tissue',
 'SUSY',
 'Arcene',
 'Bias correction of numerical prediction model temperature forecast',
 'Rocket League Skillshots',
 'Climate Model Simulation Crashes',
 'BuddyMove Data Set',
 'LT-FS-ID: Intrusion detection in WSNs',
 'Accelerometer',
 'Restaurant & consumer data',
 'Dataset based on UWB for Clinical Establishments',
 'Buzz in social media',
 'Speaker Accent Recognition',
 'Dataset for Sensorless Drive Diagnosis',
 'Amphibians',
 'University',
 'Similarity Prediction',
 'Vehicle routing and scheduling problems',
 'ICU',
 'Deepfakes: Medical Image Tamper Detection',
 'QSAR biodegradation',
 'Wave Energy Converters',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'TUANDROMD (Tezpur University Android Malware Dataset)',
 'Wikipedia Math Essentials',
 'Physicochemical Properties of Protein Tertiary Structure',
 'Devanagari Handwritten Character Dataset',
 'Mechanical Analysis',
 'Localization Data for Person Activity',
 'QSAR aquatic toxicity',
 'PEMS-SF',
 'Anuran Calls (MFCCs)',
 'PM2.5 Data of Five Chinese Cities',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'SkillCraft1 Master Table Dataset',
 'Dorothea',
 'Open Web Text Corpus',
 'Shill Bidding Dataset',
 'Turkish Music Emotion',
 'Synthetic Control Chart Time Series',
 'Influenza Outbreak Event Prediction via Twitter',
 'HEPMASS',
 'sEMG for Basic Hand movements',
 'SML2010',
 'TV News Channel Commercial Detection Dataset',
 '3D Road Network (North Jutland, Denmark)',
 'Immunotherapy Dataset',
 'Swarm Behaviour',
 'Libras Movement',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'Somerville Happiness Survey',
 'EMG dataset in Lower Limb',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'Avila',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Student Loan Relational',
 'Urban Land Cover',
 'Visegrad Group companies data',
 'Breath Metabolomics',
 'Wheat Kernels',
 'Gait Classification',
 'Qualitative_Bankruptcy',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'seismic-bumps',
 'Twitter Data set for Arabic Sentiment Analysis',
 'MaskReminder',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Chemical Composition of Ceramic Samples',
 '2D elastodynamic metamaterials',
 'Stock keeping units',
 'Early biomarkers of Parkinson’s disease based on natural connected speech',
 'Parkinson Dataset with replicated acoustic features',
 'One-hundred plant species leaves data set',
 'Dishonest Internet users Dataset',
 'Farm Ads',
 'Grammatical Facial Expressions',
 'Motion Capture Hand Postures',
 'EMG Physical Action Data Set',
 'Shell Commands Used by Participants of Hands-on Cybersecurity Training',
 'SGEMM GPU kernel performance',
 'Gisette',
 'Forest type mapping',
 'URL Reputation',
 'HCC Survival',
 'Simulated Falls and Daily Living Activities Data Set',
 'Carbon Nanotubes',
 'Gas sensor arrays in open sampling settings',
 'Internet Usage Data',
 'Gas sensor array exposed to turbulent gas mixtures',
 'Image Recognition Task Execution Times in Mobile Edge Computing',
 'Gesture Phase Segmentation',
 'Multi-view Brain Networks',
 'Twin gas sensor arrays',
 'Activity recognition using wearable physiological measurements',
 'CNAE-9',
 'Anticancer peptides',
 'Real-time Election Results: Portugal 2019',
 'Character Font Images',
 'A study of Asian Religious and Biblical Texts',
 'DrivFace',
 'Ultrasonic flowmeter diagnostics',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'Character Trajectories',
 'Non Verbal Tourists',
 'Simulated data for survival modelling',
 'Dynamic Features of VirusShare Executables',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 '3W dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'TUNADROMD',
 'Artificial Characters',
 'wiki4HE',
 'SCADI',
 'Period Changer',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'User Identification From Walking Activity',
 'NoisyOffice',
 'Sundanese Twitter Dataset',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'REALDISP Activity Recognition Dataset',
 'Gender Gap in Spanish WP',
 'Cryotherapy Dataset',
 'Hill-Valley',
 'Bengali Hate Speech Detection Dataset',
 'Spoken Arabic Digit',
 'Crowdsourced Mapping',
 'Crop mapping using fused optical-radar data set',
 'MiniBooNE particle identification',
 'Relative location of CT slices on axial axis',
 'Pedal Me Bicycle Deliveries',
 'NIPS Conference Papers 1987-2015',
 'Guitar Chords finger positions',
 'Volcanoes on Venus - JARtool experiment',
 'Online Handwritten Assamese Characters Dataset',
 'KEGG Metabolic Relation Network (Directed)',
 'LSVT Voice Rehabilitation',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Gas sensor array under flow modulation',
 'Refractive errors',
 'Sentence Classification',
 'microblogPCU',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Wilt',
 'Sirtuin6 Small Molecules',
 'Indoor User Movement Prediction from RSS data',
 'Query Analytics Workloads Dataset',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Optical Interconnection Network',
 'Horton General Hospital',
 'Container Crane Controller Data Set',
 'Reuter_50_50',
 'Multimodal Damage Identification for Humanitarian Computing',
 'StoneFlakes',
 'Eco-hotel',
 '9mers from cullpdb',
 'Ajwa or Medjool',
 'KASANDR',
 'Kinship',
 'Dexter',
 'Othello Domain Theory',
 'YouTube Comedy Slam Preference Data',
 'Folio',
 'p53 Mutants',
 'Dodgers Loop Sensor',
 'BLOGGER',
 'DSRC Vehicle Communications',
 'Average Localization Error (ALE) in sensor node localization process in WSNs',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 "Mesothelioma's disease data set",
 'Low Resolution Spectrometer',
 'MicroMass',
 'QSAR Bioconcentration classes dataset',
 'Wisesight Sentiment Corpus',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Repeat Consumption Matrices',
 'Labeled Text Forum Threads Dataset',
 'Sponge',
 'Person Classification Gait Data',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'UJIIndoorLoc-Mag',
 'MEx',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Wave Energy Converters',
 'Physical Unclonable Functions',
 'LastFM Asia Social Network',
 'Roman Urdu Data Set',
 '181 early modern English plays: Transcriptions of early editions in TEI encoding',
 'Record Linkage Comparison Patterns',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Exasens',
 "Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson's Disease",
 'Bach Choral Harmony',
 '2.4 GHZ Indoor Channel Measurements',
 'Facebook Large Page-Page Network',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'SIFT10M',
 'Wikipedia Math Essentials',
 'Connectionist Bench (Nettalk Corpus)',
 'Victorian Era Authorship Attribution',
 'IDA2016Challenge',
 'selfBACK',
 'HIV-1 protease cleavage',
 'extention of Z-Alizadeh sani dataset',
 'CLINC150',
 'QSAR oral toxicity',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'Quadruped Mammals',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'REJAFADA',
 'Z-Alizadeh Sani',
 'Demospongiae',
 'Roman Urdu Sentiment Analysis Dataset (RUSAD)',
 'User Profiling and Abusive Language Detection Dataset',
 'Nomao',
 'Predict keywords activities in a online social media',
 'UJI Pen Characters',
 'Stock keeping units',
 'QSAR fish bioconcentration factor (BCF)',
 'Meta-data',
 'CalIt2 Building People Counts',
 'Vicon Physical Action Data Set',
 'Quality Assessment of Digital Colposcopies',
 'Pseudo Periodic Synthetic Time Series',
 'Newspaper and magazine images segmentation dataset',
 'Detect Malacious Executable(AntiVirus)',
 'GitHub MUSAE',
 'chipseq',
 'MoCap Hand Postures',
 'AAAI 2014 Accepted Papers',
 'Turkish Spam V01',
 'Coil 1999 Competition Data',
 ': Simulated Data set of Iraqi tourism places',
 'PANDOR',
 'BAUM-1',
 'NYSK',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Firm-Teacher_Clave-Direction_Classification',
 'QtyT40I10D100K',
 'Youtube cookery channels viewers comments in Hinglish',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'First-order theorem proving',
 'UR3 CobotOps',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'PubChem Bioassay Data',
 'Miskolc IIS Hybrid IPS',
 'M. Tuberculosis Genes',
 'Russian Corpus of Biographical Texts',
 'Reuters Transcribed Subset',
 'AAAI 2013 Accepted Papers',
 'QSAR androgen receptor',
 'Discrete Tone Image Dataset',

In [ ]:
# Falling short of time hence submitting without creating a dataframe with the above data